# Generated by Django 5.1.9 on 2025-05-10 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_companyprofile_office_phone_number'),
        ('management', '0004_remove_swotanalysis_analysis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SWOTQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True, verbose_name='Question')),
                ('category', models.CharField(choices=[('Strength', 'Strength'), ('Weakness', 'Weakness'), ('Opportunity', 'Opportunity'), ('Threat', 'Threat')], max_length=50, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'SWOT Question',
                'verbose_name_plural': 'SWOT Questions',
            },
        ),
        migrations.RemoveField(
            model_name='swotmatrix',
            name='opportunities',
        ),
        migrations.RemoveField(
            model_name='swotmatrix',
            name='strengths',
        ),
        migrations.RemoveField(
            model_name='swotmatrix',
            name='threats',
        ),
        migrations.RemoveField(
            model_name='swotmatrix',
            name='weaknesses',
        ),
        migrations.AddField(
            model_name='swotmatrix',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='SWOTOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Answer')),
                ('category', models.CharField(choices=[('Strength', 'Strength'), ('Weakness', 'Weakness'), ('Opportunity', 'Opportunity'), ('Threat', 'Threat')], max_length=20, verbose_name='Category')),
                ('external_factor', models.CharField(blank=True, choices=[('Political', 'Political (e.g., regulations, government policies)'), ('Economic', 'Economic (e.g., market trends, inflation)'), ('Social', 'Social (e.g., cultural shifts, demographics)'), ('Technological', 'Technological (e.g., innovation, automation)'), ('Environmental', 'Environmental (e.g., sustainability, climate)'), ('Legal', 'Legal (e.g., compliance, laws)')], max_length=50, verbose_name='External Factor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyprofile', verbose_name='Company')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.swotquestion', verbose_name='Question')),
            ],
        ),
        migrations.AddField(
            model_name='swotmatrix',
            name='options',
            field=models.ManyToManyField(related_name='swot_matrices', to='management.swotoption', verbose_name='SWOT Options'),
        ),
        migrations.DeleteModel(
            name='SWOTAnalysis',
        ),
        migrations.DeleteModel(
            name='SWOTOpportunityOption',
        ),
        migrations.DeleteModel(
            name='SWOTStrengthOption',
        ),
        migrations.DeleteModel(
            name='SWOTThreatOption',
        ),
        migrations.DeleteModel(
            name='SWOTWeaknessOption',
        ),
        migrations.AddIndex(
            model_name='swotoption',
            index=models.Index(fields=['company', 'category'], name='management__company_de2214_idx'),
        ),
        migrations.AddIndex(
            model_name='swotoption',
            index=models.Index(fields=['question'], name='management__questio_6608e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='swotoption',
            constraint=models.UniqueConstraint(condition=models.Q(('question__isnull', False)), fields=('company', 'question', 'category'), name='unique_company_question_category'),
        ),
    ]
