# Generated by Django 5.1.9 on 2025-05-10 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_swotquestion_remove_swotmatrix_opportunities_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='swotoption',
            options={'verbose_name': 'SWOT Option', 'verbose_name_plural': 'SWOT Options'},
        ),
        migrations.RemoveField(
            model_name='swotmatrix',
            name='status',
        ),
    ]
