# Generated by Django 5.1.9 on 2025-05-28 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0011_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="humanresource",
            options={
                "verbose_name": "منابع انسانی شرکت\u200cها",
                "verbose_name_plural": "منابع انسانی شرکت\u200cها",
            },
        ),
        migrations.AlterModelOptions(
            name="organizationchartbase",
            options={
                "verbose_name": "فایل\u200c خام نمودار سازمانی",
                "verbose_name_plural": "فایل\u200cهای خام نمودار سازمانی",
            },
        ),
    ]
