# version: '3.12'

services:
  web:
    build: .
    ports:
      - "8000:8000"  # Expose port 8000
    volumes:
      - .:/app  # Mount the current directory
    env_file:
      - .env
    depends_on:
      - redis

  celery:
    build: .
    command: celery -A config worker --beat -l INFO
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"