
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh entrypoint.sh
    ports:
      - "8000:8000"  # Expose port 8000
    volumes:
      - .:/app  # Mount the current directory
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A config worker -l INFO
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
