FIELD_FARSI_MAP = {
    "BalanceSheet": {
        "date": "تاریخ",
        "current_assets": "دارایی جاری",
        "non_current_assets": "دارایی غیر جاری",    
        "current_liabilities": "بدهی جاری",
        "long_term_liabilities": "بدهی بلندمدت",
        "equity": "حقوق صاحبان سهام",
        "revenue": "درآمد",
        "expense": "هزینه",
        "contingent_account": "حساب انتظامی",
    },
    "CurrentAsset": {
        "balance_sheet": "ترازنامه",
        "name": "نام",
        "amount": "مبلغ",
    },
    "Cash": {
        "current_asset": "دارایی جاری",
        "cash_in_hand": "صندوق",
        "bank_balances": "بانک‌ها",
        "petty_cash": "تنخواه‌گردان‌ها",
        "cash_in_transit": "وجوه در راه",
    },
    "ShortTermInvestment": {
        "current_asset": "دارایی جاری",
        "short_term_deposits": "سپرده‌های کوتاه مدت",
        "tradable_stocks": "سهام بورسی قابل معامله",
        "participation_bonds": "اوراق مشارکت",
        "etf_investment_fund": "صندوق سرمایه گذاری قابل معامله (ETF)",
        "other_short_term_investments": "سایر سرمایه گذاری‌های کوتاه‌مدت",
        "short_term_investment_impairment": "ذخیره‌ی کاهش ارزش سرمایه‌گذاری‌های کوتاه‌مدت",
    },
    "TradeReceivable": {
        "current_asset": "دارایی جاری",
        "trade_accounts_receivable": "حساب‌های دریافتنی تجاری",
        "trade_notes_receivable": "اسناد دریافتنی تجاری",
        "receivables_in_litigation": "حساب‌های دریافتنی در دعاوی حقوقی",
        "notes_in_collection": "اسناد درجریان وصول",
        "returned_cheques": "اسناد دریافتنی واخواستی (چک‌های برگشتی مشتری)",
        "doubtful_receivables_provision": "ذخیره‌ی مطالبات مشکوک‌الوصول",
    },
    "NonTradeReceivable": {
        "current_asset": "دارایی جاری",
        "non_trade_accounts_receivable": "حساب‌های دریافتنی غیرتجاری",
        "non_trade_notes_receivable": "اسناد دریافتنی غیرتجاری",
        "employee_receivables": "حساب‌های دریافتنی از کارکنان (وام و مساعده)",
        "director_receivables": "حساب‌های دریافتنی از مدیران و اعضای هیات مدیره",
        "related_companies_receivables": "حساب‌های دریافتنی از شرکت‌ها و اشخاص وابسته",
        "vat_receivable": "مالیات بر ارزش افزوده",
        "deposits_with_others": "سپرده‌های ما نزد دیگران",
        "dividends_receivable": "سود سهام دریافتنی",
    },
    "ShareholderReceivable": {
        "current_asset": "دارایی جاری",
        "amount": "مبلغ",
    },
    "Inventory": {
        "current_asset": "دارایی جاری",
        "raw_materials": "موجودی مواد اولیه",
        "work_in_progress": "موجودی کالای درجریان ساخت",
        "finished_goods": "موجودی کالای ساخته شده و آماده فروش",
        "purchased_goods_for_sale": "موجودی کالای خریداری شده جهت فروش",
        "spare_parts": "موجودی قطعات و لوازم یدکی",
        "packaging_materials": "موجود مواد بسته بندی",
        "consignment_goods_with_others": "کالای امانی نزد دیگران",
        "idle_items": "موجودی اقلام راکد",
        "scrap_raw_materials": "موجودی ضایعات مواد اولیه",
        "inventory_impairment": "ذخیره کاهش ارزش موجودی",
    },
    "OrdersAndPrepayments": {
        "current_asset": "دارایی جاری",
        "prepaid_goods_and_services": "پیش‌پرداخت خرید کالا و خدمات",
        "prepaid_income_tax": "پیش‌پرداخت مالیات عملکرد",
        "prepaid_rent": "پیش‌پرداخت اجاره",
        "prepaid_insurance": "پیش‌پرداخت بیمه",
        "orders_in_transit": "سفارشات در راه",
        "prepaid_loans": "پیش پرداخت تسهیلات",
        "prepaid_interest_on_loans": "پیش پرداخت سود تسهیلات",
        "other_prepayments": "سایر پیش‌پرداخت‌ها",
    },
    "AssetsHeldForSale": {
        "current_asset": "دارایی جاری",
        "assets_held_for_sale": "ارزش دارایی نگهداری شده برای فروش",
        "impairment_reserve": "ذخیره کاهش ارزش دارایی",
    },
    "FixedAsset": {
        "balance_sheet": "ترازنامه",
    },
    "IntangibleAsset": {
        "fixed_asset": "دارایی ثابت",
        "software": "نرم‌افزار",
        "royalty": "حق الامتیاز",
        "goodwill": "سرقفلی",
        "patent": "حق اختراع",
        "trademark": "علائم تجاری و برندها",
        "copyright": "حق تالیف/ حق نشر",
        "pre_operating_expenses": "هزینه های قبل از بهره برداری",
    },
    "TangibleFixedAsset": {
        "fixed_asset": "دارایی ثابت",
        "land": "زمین",
        "building": "ساختمان",
        "installations": "تاسیسات",
        "machinery_and_equipment": "ماشین‌آلات و تجهیزات",
        "vehicles": "وسایل نقلیه",
        "office_furniture": "اثاثیه اداری",
        "accumulated_depreciation": "استهلاک انباشته‌ی دارایی غیر جاری",
    },
    "AssetsInProgress": {
        "fixed_asset": "دارایی ثابت",
        "amount": "مبلغ",
    },
    "LongTermInvestment": {
        "fixed_asset": "دارایی ثابت",
        "investment_in_affiliates": "سرمایه گذاری در سهام شرکت های وابسته",
        "investment_in_subsidiaries": "سرمایه گذاری در سهام شرکت های فرعی",
        "investment_in_private_companies": "سرمایه گذاری در سهام شرکت های غیربورسی",
        "long_term_bonds": "سرمایه گذاری در اوراق مشارکت بلندمدت",
        "property_investment": "سرمایه گذاری بلند مدت در املاک",
        "long_term_deposits": "سپرده های بلند مدت",
        "long_term_participation_in_projects": "مشارکت بلند مدت در طرح ها و پروژه ها",
        "long_term_treasury_investment": "سرمایه گذاری بلند مدت در اوراق خزانه",
        "long_term_investment_impairment": "ذخیره کاهش ارزش سرمایه گذاری های بلند مدت",
    },
    "OtherNonCurrentAsset": {
        "fixed_asset": "دارایی ثابت",
        "amount": "مبلغ",
    },
    "CurrentLiability": {
        "balance_sheet": "ترازنامه",
    },
    "TradeAccountsPayable": {
        "current_liability": "بدهی جاری",
        "domestic_suppliers": "حساب ها و اسناد پرداختنی به تامین کننده داخلی",
        "foreign_suppliers": "حساب ها و اسناد پرداختنی به تامین کننده خارجی",
    },
    "NonTradeAccountsPayable": {
        "current_liability": "بدهی جاری",
        "salaries_payable": "حقوق و دستمزد پرداختنی",
        "social_security_payable": "سازمان تامین اجتماعی (حق بیمه‌ی کارکنان)",
        "deposits_from_entities": "سپرده دریافتی از اشخاص حقیقی و حقوقی",
        "deposits_from_individuals": "سپرده دریافتنی از اشخاص حقیقی",
        "accrued_unpaid_expenses_provision": "ذخیره‌ی هزینه‌های تحقق‌یافته‌ی پرداخت‌نشده",
    },
    "ShareholderPayables": {
        "current_liability": "بدهی جاری",
        "amount": "مبلغ",
    },
    "DividendsPayable": {
        "current_liability": "بدهی جاری",
        "dividends_payable_to_individuals": "سود سهام پرداختنی به اشخاص",
        "dividends_payable_to_shareholders": "سود سهام پرداختنی به سهامداران",
        "dividends_payable_from_previous_years": "سود سهام پرداختنی سنوات گذشته",
    },
    "ShortTermLoans": {
        "current_liability": "بدهی جاری",
        "loans_from_banks": "تسهیلات مالی دریافتی از بانک‌ها",
        "loans_from_individuals": "تسهیلات مالی دریافتی از اشخاص",
    },
    "AdvancesAndDeposits": {
        "current_liability": "بدهی جاری",
        "advances_for_goods_sales": "پیش‌دریافت فروش کالا",
        "advances_for_services": "پیش‌دریافت ارائه خدمات",
        "advances_for_contracts": "پیش‌دریافت قرارداد پیمانکاری",
        "deposits_from_others": "سپرده های دیگران نزد ما",
    },
    "LiabilitiesRelatedToAssetsHeldForSale": {
        "current_liability": "بدهی جاری",
        "related_loans": "تسهیلات دریافت شده مربوطه",
        "related_major_repairs_liability": "بدهی بابت تعمیرات اساسی مربوطه",
        "related_deferred_tax": "مالیات معوق مربوطه",
        "related_expert_fees_payable": "حق‌الزحمه‌ی پرداختنی کارشناس رسمی",
    },
    "TaxProvision": {
        "current_liability": "بدهی جاری",
        "amount": "مبلغ",
    },
    "TaxPayable": {
        "current_liability": "بدهی جاری",
        "payroll_tax": "سازمان امور مالیاتی (مالیات حقوق)",
        "withholding_tax": "سازمان امور مالیاتی (مالیات تکلیفی)",
        "vat_payable": "سازمان امور مالیاتی (مالیات ارزش افزوده)",
        "income_tax_payable": "سازمان امور مالیاتی (مالیات عملکرد)",
    },
    "LongTermLiability": {
        "balance_sheet": "ترازنامه",
    },
    "LongTermAccountsPayable": {
        "long_term_liability": "بدهی بلندمدت",
        "long_term_notes_payable": "اسناد پرداختنی بلند مدت",
        "long_term_accounts_payable": "حساب های پرداختنی بلند مدت",
    },
    "LongTermLoans": {
        "long_term_liability": "بدهی بلندمدت",
        "loans_from_banks": "تسهیلات مالی دریافتی بلندمدت از بانک‌ها",
    },
    "LongTermProvisions": {
        "long_term_liability": "بدهی بلندمدت",
        "employee_end_of_service_benefits": "ذخیره‌ی مزایای پایان خدمت کارکنان",
    },
    "Equity": {
        "balance_sheet": "ترازنامه",
    },
    "InitialCapital": {
        "equity": "حقوق صاحبان سهام",
        "amount": "مبلغ",
    },
    "CapitalIncreaseDecrease": {
        "equity": "حقوق صاحبان سهام",
        "amount": "مبلغ",
    },
    "SharePremiumReserve": {
        "equity": "حقوق صاحبان سهام",
        "amount": "مبلغ",
    },
    "ShareDiscountReserve": {
        "equity": "حقوق صاحبان سهام",
        "amount": "مبلغ",
    },
    "LegalReserve": {
        "equity": "حقوق صاحبان سهام",
        "amount": "مبلغ",
    },
    "OtherReserves": {
        "equity": "حقوق صاحبان سهام",
        "amount": "مبلغ",
    },
    "RevaluationSurplus": {
        "equity": "حقوق صاحبان سهام",
        "amount": "مبلغ",
    },
    "ForeignCurrencyTranslationDifference": {
        "equity": "حقوق صاحبان سهام",
        "amount": "مبلغ",
    },
    "RetainedEarnings": {
        "equity": "حقوق صاحبان سهام",
        "amount": "مبلغ",
    },
    "Revenue": {
        "balance_sheet": "ترازنامه",
    },
    "NetSales": {
        "revenue": "درآمد",
        "amount": "مبلغ",
    },
    "ServiceRevenue": {
        "revenue": "درآمد",
        "amount": "مبلغ",
    },
    "ForeignCurrencyRevenue": {
        "revenue": "درآمد",
        "amount": "مبلغ",
    },
    "OtherOperatingRevenue": {
        "revenue": "درآمد",
        "amount": "مبلغ",
    },
    "Expense": {
        "balance_sheet": "ترازنامه",
    },
    "ProductionCosts": {
        "expense": "هزینه",
        "direct_materials": "مواد مستقیم مصرفی",
        "direct_labor": "دستمزد مستقیم - تولید",
        "machinery_depreciation": "استهلاک ماشین آلات",
        "production_line_insurance": "بیمه خط تولید",
        "energy_and_fuel": "انرژی و سوخت مصرفی تولید",
        "equipment_maintenance": "تعمیر و نگهداری تجهیزات تولید",
        "production_consumables": "ابزار مصرفی تولید",
        "production_rent": "اجاره فضای تولید",
        "raw_material_transport": "حمل و نقل مواد اولیه",
    },
    "DistributionAndMarketingCosts": {
        "expense": "هزینه",
        "marketing_salaries": "هزینه حقوق و دستمزد - بازاریابی و فروش",
        "advertising_and_promotions": "هزینه‌های تبلیغات، بازاریابی، کاتالوگ و بروشور",
        "warehousing_costs": "هزینه‌ی انبارداری",
        "transportation_to_customers": "حمل و نقل کالا به مشتری",
        "after_sales_services": "هزینه خدمات پس از فروش",
        "sales_commissions": "پورسانت فروش",
        "packaging_and_labeling": "بسته بندی و لیبل زنی",
        "exhibitions_and_events": "نمایشگاه ها و رویدادهای تبلیغاتی",
    },
    "GeneralAndAdministrativeCosts": {
        "expense": "هزینه",
        "administrative_salaries_payable": "حقوق و دستمزد پرداختنی - اداری",
        "head_office_rent": "اجاره دفتر مرکزی",
        "utility_bills": "قبوض",
        "office_supplies": "هزینه ملزومات",
        "administrative_assets_depreciation": "استهلاک دارایی های اداری",
        "general_insurance": "بیمه های عمومی",
        "audit_and_consulting_fees": "هزینه حسابرسی و مشاوره",
        "hospitality_and_transport": "پذیرایی و ایاب و ذهاب",
    },
    "FinancialCosts": {
        "expense": "هزینه",
        "bank_interest_and_fees": "سود و کارمزد تسهیلات بانکی",
        "loan_late_penalties": "جرائم تاخیر در بازپرداخت وام",
        "guarantee_fees": "هزینه های کارمزد ضمانت نامه ها",
        "discounting_expenses_on_receivables": "هزینه های تنزیل اسناد دریافتنی",
        "fund_transfer_and_bank_services": "هزینه انتقال وجه و خدمات بانکی",
    },
    "OtherOperatingCosts": {
        "expense": "هزینه",
        "bad_debts_and_written_off_expense": "هزینه‌ی مطالبات مشکوک‌الوصول و سوخت‌شده",
        "fx_non_operating_gain_loss": "سود و زیان تسعیر دارایی‌ها و بدهی‌های ارزی غیرمرتبط با عملیات",
        "impairment_short_term_investments": "هزینه کاهش ارزش سرمایه گذاری های کوتاه مدت",
        "inventory_write_down": "هزینه کاهش ارزش موجودی",
        "asset_impairment": "هزینه کاهش ارزش دارایی",
        "impairment_long_term_investments": "هزینه کاهش ارزش سرمایه گذاری های بلند مدت",
        "fx_operating_gain_loss": "سود و زیان ناشی از تسعیر دارایی‌ها و بدهی‌های ارزی عملیاتی",
    },
    "ContingentAccount": {
        "balance_sheet": "ترازنامه",
    },
    "ContingentAccounts": {
        "contingent_account": "حساب انتظامی",
        "our_accounts_with_others": "حساب انتظامی ما نزد دیگران",
        "others_accounts_with_us": "حساب انتظامی دیگران نزد ما",
    },
    "ContingentCounterparties": {
        "contingent_account": "حساب انتظامی",
        "our_counterparties_with_others": "طرف حساب انتظامی ما نزد دیگران",
        "others_counterparties_with_us": "طرف حساب انتظامی دیگران نزد ما",
        "amount": "مبلغ",
    },
}