# Generated by Django 5.1.8 on 2025-04-29 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_packagepermission_userpermission'),
        ('packages', '0008_alter_subscription_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagepermission',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='packages.package'),
        ),
        migrations.AddField(
            model_name='packagepermission',
            name='service',
            field=models.ManyToManyField(blank=True, null=True, related_name='permissions', to='packages.service'),
        ),
    ]
