# Generated by Django 5.1.2 on 2024-10-21 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_rename_special_filed_companyprofile_special_field_and_more'),
        ('core', '0004_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institute',
            name='province',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='Institute',
        ),
    ]
