# Generated by Django 5.1.8 on 2025-04-21 05:57

import apps.core.validators
import django.core.validators
import django.db.models.deletion
import apps.finance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="Year")),
                (
                    "month",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(13),
                        ],
                        verbose_name="Month",
                    ),
                ),
                (
                    "is_tax_record",
                    models.BooleanField(default=False, verbose_name="Is Tax Record"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_records",
                        to="company.companyprofile",
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Asset",
                "verbose_name_plural": "Financial Assets",
                "unique_together": {("company", "year", "month")},
            },
        ),
        migrations.CreateModel(
            name="FinancialData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Define whether the reports are published and shown to the user or not.",
                        verbose_name="Publish for user",
                    ),
                ),
                (
                    "current_asset",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Current Asset",
                    ),
                ),
                (
                    "non_current_asset",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Non-Current Asset",
                    ),
                ),
                (
                    "total_asset",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Total Asset",
                    ),
                ),
                (
                    "current_debt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Current Debt",
                    ),
                ),
                (
                    "non_current_debt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Non-Current Debt",
                    ),
                ),
                (
                    "total_debt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Total Debt",
                    ),
                ),
                (
                    "total_equity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Total Equity",
                    ),
                ),
                (
                    "total_sum_equity_debt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Total Equity and Debt Sum",
                    ),
                ),
                (
                    "gross_profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Gross Profit",
                    ),
                ),
                (
                    "net_sale",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Net Sale",
                    ),
                ),
                (
                    "operational_income_expense",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Operational Income Expense",
                    ),
                ),
                (
                    "marketing_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Marketing Fee",
                    ),
                ),
                (
                    "inventory_average",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Inventory Average",
                    ),
                ),
                (
                    "operational_profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Operational Profit",
                    ),
                ),
                (
                    "proceed_profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Proceed Profit",
                    ),
                ),
                (
                    "net_profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Net Profit",
                    ),
                ),
                (
                    "consuming_material",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Consuming Material",
                    ),
                ),
                (
                    "production_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Production Fee",
                    ),
                ),
                (
                    "construction_overhead",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Construction Overhead",
                    ),
                ),
                (
                    "production_total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Total Production Price",
                    ),
                ),
                (
                    "salary_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Salary Fee",
                    ),
                ),
                (
                    "salary_production_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Production Salary Fee",
                    ),
                ),
                (
                    "usability",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Usability",
                    ),
                ),
                (
                    "efficiency",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Efficiency",
                    ),
                ),
                (
                    "roa",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Return on Assets (ROA)",
                    ),
                ),
                (
                    "roab",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Return on Assets Before Tax (ROAB)",
                    ),
                ),
                (
                    "roe",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Return on Equity (ROE)",
                    ),
                ),
                (
                    "gross_profit_margin",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Gross Profit Margin",
                    ),
                ),
                (
                    "profit_margin_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Profit Margin Ratio",
                    ),
                ),
                (
                    "debt_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Debt Ratio",
                    ),
                ),
                (
                    "capital_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Capital Ratio",
                    ),
                ),
                (
                    "proprietary_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Proprietary Ratio",
                    ),
                ),
                (
                    "equity_per_total_debt_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Equity to Total Debt Ratio",
                    ),
                ),
                (
                    "equity_per_total_non_current_asset_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Equity to Non-Current Asset Ratio",
                    ),
                ),
                (
                    "current_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Current Ratio",
                    ),
                ),
                (
                    "instant_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Instant Ratio",
                    ),
                ),
                (
                    "stock_turnover",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Stock Turnover",
                    ),
                ),
                (
                    "altman_bankrupsy_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Altman Bankruptcy Ratio",
                    ),
                ),
                (
                    "trade_payable",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Trade Payable",
                    ),
                ),
                (
                    "advance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Advance",
                    ),
                ),
                (
                    "reserves",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Reserves",
                    ),
                ),
                (
                    "long_term_payable",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Long Term Payable",
                    ),
                ),
                (
                    "employee_termination_benefit_reserve",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Employee Termination Benefit Reserve",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "financial_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calculated_data",
                        to="finance.financialasset",
                        verbose_name="Financial Asset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Data",
                "verbose_name_plural": "Financial Datas",
            },
        ),
        migrations.CreateModel(
            name="BalanceReportFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(verbose_name="Year")),
                (
                    "is_saved",
                    models.BooleanField(default=True, verbose_name="Is Saved"),
                ),
                ("is_sent", models.BooleanField(default=False, verbose_name="Is Sent")),
                (
                    "month",
                    models.CharField(
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("11", "11"),
                            ("12", "12"),
                            ("13", "13"),
                        ],
                        max_length=2,
                        verbose_name="Month",
                    ),
                ),
                (
                    "balance_report_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.finance.models.get_non_tax_file_upload_path,
                        validators=[apps.core.validators.pdf_file_validator],
                        verbose_name="Balance Report File",
                    ),
                ),
                (
                    "profit_loss_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.finance.models.get_non_tax_file_upload_path,
                        validators=[apps.core.validators.pdf_file_validator],
                        verbose_name="Profit Loss File",
                    ),
                ),
                (
                    "sold_product_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.finance.models.get_non_tax_file_upload_path,
                        validators=[apps.core.validators.pdf_file_validator],
                        verbose_name="Sold Product File",
                    ),
                ),
                (
                    "account_turnover_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.finance.models.get_non_tax_file_upload_path,
                        validators=[apps.core.validators.pdf_file_validator],
                        verbose_name="Account Turn Over File",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reportfiles",
                        to="company.companyprofile",
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Finance Balance Report File",
                "verbose_name_plural": "Finance Balance Reports File",
                "unique_together": {("company", "month", "year")},
            },
        ),
        migrations.CreateModel(
            name="FinanceExcelFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "finance_excel_file",
                    models.FileField(
                        upload_to=apps.finance.models.get_finance_excel_file_upload_path,
                        validators=[apps.core.validators.excel_file_validator],
                        verbose_name="Finance Excel File",
                    ),
                ),
                (
                    "is_saved",
                    models.BooleanField(default=True, verbose_name="Is Saved"),
                ),
                ("is_sent", models.BooleanField(default=False, verbose_name="Is Sent")),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="excelfiles",
                        to="company.companyprofile",
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Finance Excel File",
                "verbose_name_plural": "Finance Excel Files",
                "unique_together": {("company", "finance_excel_file")},
            },
        ),
        migrations.CreateModel(
            name="BalanceReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "advance_payment",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Advance Payment",
                    ),
                ),
                (
                    "first_period_inventory",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="First Period Inventory",
                    ),
                ),
                (
                    "end_period_inventory",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="End Period Inventory",
                    ),
                ),
                (
                    "trade_receivable",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Recievable Trade Account",
                    ),
                ),
                (
                    "short_term_investment",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Short term Investment",
                    ),
                ),
                (
                    "cash_balance",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Cash Balance",
                    ),
                ),
                (
                    "held_non_current_asset",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Non-current assets held for sale",
                    ),
                ),
                (
                    "current_shareholder_asset",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Current Partner/Shareholder",
                    ),
                ),
                (
                    "total_current_asset",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Total Current Asset",
                    ),
                ),
                (
                    "tangible_fixed_asset",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Tangible Fixed Asset",
                    ),
                ),
                (
                    "property_investment",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Property Investment",
                    ),
                ),
                (
                    "intangible_asset",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Intangible Asset",
                    ),
                ),
                (
                    "long_term_investment",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Long Term Investment",
                    ),
                ),
                (
                    "long_term_receivable",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Long Term Receivable",
                    ),
                ),
                (
                    "other_asset",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Other Asset",
                    ),
                ),
                (
                    "total_non_current_asset",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Total Non-Current Asset",
                    ),
                ),
                (
                    "capital",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Wealth",
                    ),
                ),
                (
                    "capital_increase",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Wealth Increase",
                    ),
                ),
                (
                    "share_spend",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Share Spend",
                    ),
                ),
                (
                    "treasury_share_spend",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Treasury Share Spend",
                    ),
                ),
                (
                    "legal_reserve",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Legal Reserve",
                    ),
                ),
                (
                    "other_reserve",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Other Reserve",
                    ),
                ),
                (
                    "revaluation_surplus",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Asset Revaluation Surplus and Other Unrealized Gains",
                    ),
                ),
                (
                    "accumulated_profit_loss",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Accumulated Profit and Loss",
                    ),
                ),
                (
                    "treasury_share",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Treasury Share",
                    ),
                ),
                (
                    "ownership_right_total",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Ownership right total",
                    ),
                ),
                (
                    "trade_payable",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Trade Payable",
                    ),
                ),
                (
                    "paid_tax",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Paid Tax",
                    ),
                ),
                (
                    "dividend_payable",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Dividend Payable",
                    ),
                ),
                (
                    "financial_facility",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Financial Facility",
                    ),
                ),
                (
                    "reserves",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Reserves",
                    ),
                ),
                (
                    "advance",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Advance",
                    ),
                ),
                (
                    "held_for_sale_liability",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Liability related to non-current asset held for sale",
                    ),
                ),
                (
                    "current_shareholder_debt",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Current Partner/Shareholder",
                    ),
                ),
                (
                    "total_current_debt",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Total Current Debt",
                    ),
                ),
                (
                    "long_term_payable",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Longterm Payable",
                    ),
                ),
                (
                    "long_term_financial",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Longterm Financial Facilities",
                    ),
                ),
                (
                    "employee_termination_benefit_reserve",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Reserve Employee Termination Benefit",
                    ),
                ),
                (
                    "total_non_current_debt",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Total Non-Current Debt",
                    ),
                ),
                (
                    "net_sale",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Net Sale",
                    ),
                ),
                (
                    "net_profit",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Net Profit",
                    ),
                ),
                (
                    "financial_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balance_reports",
                        to="finance.financialasset",
                        verbose_name="Financial Asset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Balance Report",
                "verbose_name_plural": "Balance Reports",
                "unique_together": {("financial_asset",)},
            },
        ),
        migrations.CreateModel(
            name="AccountTurnOver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profit_after_tax",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Profit After Tax",
                    ),
                ),
                (
                    "first_year_accumulated_profit",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="First Year  Accumulated Profit",
                    ),
                ),
                (
                    "correcting_mistake",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Correcting Mistake",
                    ),
                ),
                (
                    "accounting_method_change",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Accounting Method Change",
                    ),
                ),
                (
                    "first_year_accumulated_profit_balanced",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="First Year`s Accumulated Profit Balanced",
                    ),
                ),
                (
                    "transfer_from_reserve",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Transfer From Reserve",
                    ),
                ),
                (
                    "other_account_turnover",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Other Account Turnover",
                    ),
                ),
                (
                    "allocable_profit",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Allocable Profit",
                    ),
                ),
                (
                    "share_profit",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Share Profit",
                    ),
                ),
                (
                    "legal_reserve",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Legal Reserve",
                    ),
                ),
                (
                    "wealth_increase",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Wealth Increase",
                    ),
                ),
                (
                    "current_wealt_increase",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Current Wealt Increase",
                    ),
                ),
                (
                    "other_reserves",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Other Reserves",
                    ),
                ),
                (
                    "treasury_share_purchase",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Treasury Share Purchase",
                    ),
                ),
                (
                    "treasury_share_sale",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Treasury Share Sale",
                    ),
                ),
                (
                    "treasury_share_sale_profit",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Treasury Share Sale Profit",
                    ),
                ),
                (
                    "board_reward",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Board Reward",
                    ),
                ),
                (
                    "other_profit",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Other Profit",
                    ),
                ),
                (
                    "total_allocated_profit",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Total Allocated Profit",
                    ),
                ),
                (
                    "end_year_accumulated_profit",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="End Year`s Accumulated profit",
                    ),
                ),
                (
                    "financial_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_turnovers",
                        to="finance.financialasset",
                        verbose_name="Financial Asset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Account TurnOver",
                "verbose_name_plural": "Accounts Turnovers",
                "unique_together": {("financial_asset",)},
            },
        ),
        migrations.CreateModel(
            name="AnalysisReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[("m", "Monthly"), ("y", "Yearly")],
                        default="y",
                        max_length=7,
                        verbose_name="Period",
                    ),
                ),
                (
                    "chart_name",
                    models.CharField(
                        choices=[
                            ("debt", "Debt Chart"),
                            ("asset", "Asset Chart"),
                            ("sale", "Sale Chart"),
                            ("equity", "Equity Chart"),
                            ("life_cycle", "Life Cycle Chart"),
                            ("bankrupsy", "Bankrupsy Chart"),
                            ("profitability", "Profitability Chart"),
                            ("salary", "Salary Chart"),
                            ("inventory", "Inventory Chart"),
                            ("agility", "Agility Chart"),
                            ("liquidity", "Liquidity Chart"),
                            ("leverage", "Leverage Chart"),
                            ("cost", "Cost Chart"),
                            ("profit", "Profit Chart"),
                        ],
                        help_text="Enter the name of each chart",
                        max_length=15,
                        verbose_name="Chart Name",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Enter the analysis text for each chart",
                        verbose_name="Analysis Text",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Select to publish the analysis report",
                        verbose_name="Published",
                    ),
                ),
                (
                    "calculated_data",
                    models.ForeignKey(
                        help_text="Select company assosiated with the year for entering the analysis text report. it would be better to only choose the last yaer of each company",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_reports",
                        to="finance.financialdata",
                        verbose_name="Calculated Data",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analysis Report",
                "verbose_name_plural": "Analysis Reports",
                "unique_together": {("chart_name", "calculated_data")},
            },
        ),
        migrations.CreateModel(
            name="ProfitLossStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operational_income",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Operational Income",
                    ),
                ),
                (
                    "operational_income_expense",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Operational Income Expense",
                    ),
                ),
                (
                    "gross_profit",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Gross Profit",
                    ),
                ),
                (
                    "salary_fee",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Salary Fee",
                    ),
                ),
                (
                    "marketing_fee",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Marketing Fee",
                    ),
                ),
                (
                    "doubtful_burnt_claims_fee",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Doubtful Burnt Claims Fee",
                    ),
                ),
                (
                    "attendance_fee",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Attendance Fee",
                    ),
                ),
                (
                    "accounting_fee",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Accounting Fee",
                    ),
                ),
                (
                    "consulting_fee",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Consulting Fee",
                    ),
                ),
                (
                    "rental_fee",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Rental Fee",
                    ),
                ),
                (
                    "other_general_expense",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Other General Expense",
                    ),
                ),
                (
                    "total_general_expense",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Total General Expense",
                    ),
                ),
                (
                    "other_operation_income",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Other Operational Income",
                    ),
                ),
                (
                    "other_operational_expense",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Other Operational Expense",
                    ),
                ),
                (
                    "operational_profit",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Operational Profit",
                    ),
                ),
                (
                    "immovable_property_sale_profit",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Immovable Property Sale Profit",
                    ),
                ),
                (
                    "other_assets_sale_profit",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Other Assets Sale Profit",
                    ),
                ),
                (
                    "material_sale_profit",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Material Sale Profit",
                    ),
                ),
                (
                    "investment_sale_profit",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Investment Sale Profit",
                    ),
                ),
                (
                    "interpretation_profit",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Interpretation Profit",
                    ),
                ),
                (
                    "dividend_profit",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Dividend Profit",
                    ),
                ),
                (
                    "investment_profit",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Investment Profit",
                    ),
                ),
                (
                    "bank_deposit_profit",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Bank Deposit Profit",
                    ),
                ),
                (
                    "rental_income",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Rental Income",
                    ),
                ),
                (
                    "incidental_income",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Incidental Income",
                    ),
                ),
                (
                    "other_non_operationl_income_expense",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Other Non-Operational Income/Expense",
                    ),
                ),
                (
                    "net_value_other_non_operationl_income_expense",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Net Value Other Non-Operational Income/Expense",
                    ),
                ),
                (
                    "financial_expense",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Financial Expense",
                    ),
                ),
                (
                    "proceed_profit",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Proceed Profit",
                    ),
                ),
                (
                    "current_year_income_tax",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Current Year Income Tax",
                    ),
                ),
                (
                    "prev_year_income_tax",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Previous Year Income Tax",
                    ),
                ),
                (
                    "profit_after_tax",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Profit After Tax",
                    ),
                ),
                (
                    "financial_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profit_loss_statements",
                        to="finance.financialasset",
                        verbose_name="Financial Asset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profit And Loss Statement",
                "verbose_name_plural": "Profit And Loss Statements",
                "unique_together": {("financial_asset",)},
            },
        ),
        migrations.CreateModel(
            name="SoldProductFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consuming_material",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Consuming Material",
                    ),
                ),
                (
                    "direct_wage",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Direct Wage",
                    ),
                ),
                (
                    "construction_overhead",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Construction Overhead",
                    ),
                ),
                (
                    "production_total_price",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Production Total Price",
                    ),
                ),
                (
                    "first_period_constructing_product_inventory",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Current Constructing Product First Period",
                    ),
                ),
                (
                    "end_period_constructing_product_inventory",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Current Constructing Product End Period",
                    ),
                ),
                (
                    "produced_product_total_price",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Produced Product Total Price",
                    ),
                ),
                (
                    "first_period_produced_inventory",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="First Period Produced Inventory",
                    ),
                ),
                (
                    "period_bought_product",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Period Bought Product",
                    ),
                ),
                (
                    "ready_for_sale_product",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Ready for Sale Product",
                    ),
                ),
                (
                    "end_period_inventory",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="End Period Inventory",
                    ),
                ),
                (
                    "product_other",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Other Product",
                    ),
                ),
                (
                    "sold_product_total_price",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="Sold Product Total Price",
                    ),
                ),
                (
                    "financial_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sold_product_fees",
                        to="finance.financialasset",
                        verbose_name="Financial Asset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sold Product Fee",
                "verbose_name_plural": "Sold Products Fee",
                "unique_together": {("financial_asset",)},
            },
        ),
        migrations.CreateModel(
            name="TaxDeclarationFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(verbose_name="Year")),
                (
                    "is_saved",
                    models.BooleanField(default=True, verbose_name="Is Saved"),
                ),
                ("is_sent", models.BooleanField(default=False, verbose_name="Is Sent")),
                (
                    "tax_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.finance.models.get_tax_file_upload_path,
                        validators=[apps.core.validators.pdf_file_validator],
                        verbose_name="File",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taxfiles",
                        to="company.companyprofile",
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Finance Tax Declaration",
                "verbose_name_plural": "Finance Tax Declarations",
                "unique_together": {("company", "year")},
            },
        ),
    ]
