# Generated by Django 5.1.9 on 2025-05-12 20:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inflation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.SmallIntegerField(
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1315, message="Year must be greater than 1315"
                            )
                        ],
                        verbose_name="سال",
                    ),
                ),
                (
                    "cpi_value",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal(
                                    "0.0040000000000000000832667268468867405317723751068115234375"
                                ),
                                message="Values must be greater than '0.004'",
                            )
                        ],
                        verbose_name="عدد شاخص",
                    ),
                ),
                (
                    "inflation_rate",
                    models.DecimalField(
                        decimal_places=1, max_digits=4, verbose_name="نرخ تورم"
                    ),
                ),
            ],
        ),
    ]
