# Generated by Django 5.1.9 on 2025-05-12 21:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_inflation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inflation",
            options={"verbose_name": "تورم", "verbose_name_plural": "تورم"},
        ),
        migrations.AlterField(
            model_name="inflation",
            name="year",
            field=models.SmallIntegerField(
                db_index=True,
                unique=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        1315, message="Year must be greater than 1315"
                    )
                ],
                verbose_name="سال",
            ),
        ),
    ]
