# Generated by Django 5.1.9 on 2025-05-13 07:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_alter_inflation_options_alter_inflation_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inflation",
            name="cpi_value",
            field=models.DecimalField(
                decimal_places=4,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal("0"), message="Values must be greater than '0'"
                    )
                ],
                verbose_name="عدد شاخص",
            ),
        ),
        migrations.AlterField(
            model_name="inflation",
            name="year",
            field=models.SmallIntegerField(
                db_index=True,
                unique=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        1315, message="Year must be greater than 1315"
                    ),
                    django.core.validators.MaxValueValidator(
                        1450, message="Year must be smaller than 1450"
                    ),
                ],
                verbose_name="سال",
            ),
        ),
    ]
