# Generated by Django 5.1.8 on 2025-04-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_alter_service_name_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='period',
            field=models.DateTimeField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annually', 'Semi-Annually'), ('annually', 'Annually')], null=True, verbose_name='Period'),
        ),
    ]
