# Generated by Django 5.1.8 on 2025-04-28 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0003_package_period"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="price",
        ),
    ]
