# Generated by Django 5.1.8 on 2025-04-29 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0006_subscription"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="expiry_date",
            new_name="expires_at",
        ),
    ]
