# Generated by Django 5.1.8 on 2025-04-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0009_alter_package_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='package',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='packages', to='packages.service', verbose_name='Services'),
        ),
    ]
