# Generated by Django 5.1.8 on 2025-04-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0011_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                max_length=10,
                verbose_name="Status",
            ),
        ),
    ]
