# Generated by Django 5.1.8 on 2025-05-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0018_subscription_service_alter_subscription_package_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='service',
        ),
        migrations.AddField(
            model_name='subscription',
            name='service',
            field=models.ManyToManyField(blank=True, related_name='subscriptions', to='packages.service', verbose_name='Service'),
        ),
    ]
