# Generated by Django 5.1.8 on 2025-05-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0019_remove_subscription_service_subscription_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='code_name',
            field=models.CharField(blank=True, max_length=2, null=True, unique=True, verbose_name='Code Name'),
        ),
    ]
