# Generated by Django 5.1.8 on 2025-05-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0020_service_code_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="code_name",
            field=models.CharField(
                blank=True,
                max_length=2,
                null=True,
                unique=True,
                verbose_name="Code Name",
            ),
        ),
    ]
