# Generated by Django 5.1.8 on 2025-05-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0022_order_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="code_name",
            field=models.CharField(
                blank=True,
                default=1,
                max_length=2,
                unique=True,
                verbose_name="Code Name",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="service",
            name="code_name",
            field=models.CharField(
                blank=True,
                default=1,
                max_length=2,
                unique=True,
                verbose_name="Code Name",
            ),
            preserve_default=False,
        ),
    ]
