# Generated by Django 5.1.8 on 2025-05-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0025_order_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled')], default='pending', max_length=10, verbose_name='Status'),
        ),
    ]
