# Generated by Django 5.1.8 on 2025-05-04 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0026_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
    ]
