# Generated by Django 5.1.9 on 2025-05-19 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0028_promotion_order_coupon_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "سفارش", "verbose_name_plural": "سفارش\u200cها"},
        ),
        migrations.AlterModelOptions(
            name="package",
            options={"verbose_name": "بسته", "verbose_name_plural": "بسته\u200cها"},
        ),
        migrations.AlterModelOptions(
            name="service",
            options={"verbose_name": "سرویس", "verbose_name_plural": "سرویس\u200cها"},
        ),
        migrations.AlterModelOptions(
            name="subscription",
            options={"verbose_name": "اشتراک", "verbose_name_plural": "اشتراک\u200cها"},
        ),
        migrations.RemoveConstraint(
            model_name="order",
            name="user_unique_package_order",
        ),
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="order",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order",
                to="packages.package",
                verbose_name="بسته",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="service",
            field=models.ManyToManyField(
                blank=True,
                related_name="orders",
                to="packages.service",
                verbose_name="سرویس",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "در انتظار"),
                    ("paid", "پرداخت شده"),
                    ("confirmed", "تایید شده"),
                    ("canceled", "لغو شده"),
                ],
                default="pending",
                max_length=10,
                verbose_name="وضعیت",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="code_name",
            field=models.CharField(
                blank=True, max_length=2, unique=True, verbose_name="کد"
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="package",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="شرح بسته"),
        ),
        migrations.AlterField(
            model_name="package",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="فعال"),
        ),
        migrations.AlterField(
            model_name="package",
            name="name",
            field=models.CharField(
                choices=[
                    ("demo", "آزمایشی"),
                    ("bronze", "برنزی"),
                    ("silver", "نقره\u200cای"),
                    ("gold", "طلایی"),
                    ("platinum", "پلاتینیوم"),
                ],
                max_length=30,
                unique=True,
                verbose_name="نام",
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="period",
            field=models.CharField(
                blank=True,
                choices=[
                    ("monthly", "ماهانه"),
                    ("quarterly", "سه ماهه"),
                    ("semi_annually", "شش ماهه"),
                    ("annually", "سالانه"),
                ],
                max_length=20,
                null=True,
                verbose_name="دوره زمانی",
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, verbose_name="قیمت"
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="services",
            field=models.ManyToManyField(
                blank=True,
                related_name="packages",
                to="packages.service",
                verbose_name="سرویس",
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
        ),
        migrations.AlterField(
            model_name="service",
            name="code_name",
            field=models.CharField(
                blank=True, max_length=2, unique=True, verbose_name="کد"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(verbose_name="شرح سرویس"),
        ),
        migrations.AlterField(
            model_name="service",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="فعال"),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(
                choices=[
                    ("financial", "مالی"),
                    ("marketing", "بازاریابی"),
                    ("management", "مدیریت"),
                    ("production", "ساخت و تولید"),
                    ("mis", "مدیریت سامانه اطلاعاتی"),
                    ("research_and_development", "تحقیق و توسعه"),
                ],
                max_length=30,
                unique=True,
                verbose_name="نام",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="period",
            field=models.CharField(
                blank=True,
                choices=[
                    ("monthly", "ماهانه"),
                    ("quarterly", "سه ماهه"),
                    ("semi_annually", "شش ماهه"),
                    ("annually", "سالانه"),
                ],
                max_length=20,
                null=True,
                verbose_name="دوره زمانی",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name="قیمت",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="duration",
            field=models.DurationField(
                blank=True,
                help_text="بازه زمانی به روز",
                null=True,
                verbose_name="بازه زمانی",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="expires_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاریخ انقضا"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="packages.package",
                verbose_name="بسته",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="purchase_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ خرید"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="service",
            field=models.ManyToManyField(
                blank=True,
                related_name="subscriptions",
                to="packages.service",
                verbose_name="سرویس",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                fields=("user", "package"), name="unique_user_package_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                fields=("user", "package"), name="unique_user_package"
            ),
        ),
    ]
