# Generated by Django 5.1.8 on 2025-05-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0013_alter_order_package"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                max_length=10,
                verbose_name="Status",
            ),
        ),
    ]
