# Generated by Django 5.1.8 on 2025-05-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0021_package_code_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="service",
            field=models.ManyToManyField(
                blank=True,
                related_name="orders",
                to="packages.service",
                verbose_name="Service",
            ),
        ),
    ]
