# Generated by Django 5.1.9 on 2025-05-18 07:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0027_remove_order_is_paid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coupon",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="کد تخفیف"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="تخفیف"
                    ),
                ),
                (
                    "validated_from",
                    models.DateTimeField(auto_now_add=True, verbose_name="معتبر از"),
                ),
                (
                    "validated_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="معتبر تا"
                    ),
                ),
                (
                    "available_for",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="تعداد قابل استفاده",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="فعال است"),
                ),
            ],
            options={
                "verbose_name": "تخفیف",
                "verbose_name_plural": "تخفیف\u200cها",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="packages.promotion",
                verbose_name="کد تخفیف",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                fields=("user", "coupon"), name="unique_user_order_coupon"
            ),
        ),
    ]
