# Generated by Django 5.1.10 on 2025-09-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="unique_id",
            field=models.CharField(
                db_index=True,
                default=35435454,
                editable=False,
                max_length=64,
                unique=True,
                verbose_name="Unique ID",
            ),
            preserve_default=False,
        ),
    ]
