# Generated by Django 5.1.10 on 2025-09-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_user_unique_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="unique_id",
            field=models.CharField(
                db_index=True, editable=False, max_length=64, verbose_name="Unique ID"
            ),
        ),
    ]
