# Generated by Django 5.1.8 on 2025-04-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_packagepermission_package_packagepermission_service"),
        ("packages", "0008_alter_subscription_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packagepermission",
            name="service",
            field=models.ManyToManyField(
                blank=True, related_name="permissions", to="packages.service"
            ),
        ),
    ]
