# Generated by Django 5.1.10 on 2025-09-03 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_user_unique_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="unique_id",
        ),
    ]
