# Generated by Django 5.1.9 on 2025-06-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_question_questionnaire_questionchoice_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"verbose_name": "Question", "verbose_name_plural": "Questions"},
        ),
        migrations.AlterModelOptions(
            name="questionchoice",
            options={
                "verbose_name": "Question Choice",
                "verbose_name_plural": "Questions Choices",
            },
        ),
        migrations.AlterModelOptions(
            name="questionnaire",
            options={
                "verbose_name": "Questionnaire",
                "verbose_name_plural": "Questionnaires",
            },
        ),
        migrations.AlterModelOptions(
            name="questionnairequestion",
            options={
                "ordering": ["order"],
                "verbose_name": "Questionnaire Question",
                "verbose_name_plural": "Questionnaires Questions",
            },
        ),
        migrations.AlterUniqueTogether(
            name="questionnairequestion",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="questionnairequestion",
            constraint=models.UniqueConstraint(
                fields=("questionnaire", "question"),
                name="unique_questionnaire_question",
            ),
        ),
    ]
