# Generated by Django 5.1.9 on 2025-06-09 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_question_options_alter_questionchoice_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"verbose_name": "سوال", "verbose_name_plural": "سوالات"},
        ),
        migrations.AlterModelOptions(
            name="questionchoice",
            options={
                "verbose_name": "گزینه\u200c سوال",
                "verbose_name_plural": "گزینه\u200cهای سوالات",
            },
        ),
        migrations.AlterModelOptions(
            name="questionnaire",
            options={
                "verbose_name": "پرسشنامه",
                "verbose_name_plural": "پرسشنامه\u200cها",
            },
        ),
        migrations.AlterModelOptions(
            name="questionnairequestion",
            options={
                "ordering": ["order"],
                "verbose_name": "سوال پرسشنامه",
                "verbose_name_plural": "سوالات پرسشنامه\u200cها",
            },
        ),
        migrations.AlterField(
            model_name="question",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.CharField(max_length=255, verbose_name="سوال"),
        ),
        migrations.AlterField(
            model_name="question",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
        ),
        migrations.AlterField(
            model_name="questionchoice",
            name="answer",
            field=models.CharField(max_length=128, verbose_name="پاسخ"),
        ),
        migrations.AlterField(
            model_name="questionchoice",
            name="points",
            field=models.IntegerField(verbose_name="امتیاز"),
        ),
        migrations.AlterField(
            model_name="questionchoice",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="core.question",
                verbose_name="سوال",
            ),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="name",
            field=models.CharField(max_length=255, verbose_name="عنوان"),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="questions",
            field=models.ManyToManyField(
                through="core.QuestionnaireQuestion",
                to="core.question",
                verbose_name="سوالات",
            ),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
        ),
        migrations.AlterField(
            model_name="questionnairequestion",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="عدد ترتیب"),
        ),
        migrations.AlterField(
            model_name="questionnairequestion",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.question",
                verbose_name="سوال",
            ),
        ),
        migrations.AlterField(
            model_name="questionnairequestion",
            name="questionnaire",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.questionnaire",
                verbose_name="پرسشنامه",
            ),
        ),
    ]
