# Generated by Django 5.1.10 on 2025-09-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_user_unique_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="unique_id",
            field=models.CharField(
                db_index=True,
                default="7fc56c2f90cd49fbb7bd935b005c1dda",
                editable=False,
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Unique ID",
            ),
        ),
    ]
