# Generated by Django 5.1.9 on 2025-06-09 04:43

import apps.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_question_options_alter_questionchoice_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnairequestion",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="تاریخ ایجاد",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="questionnairequestion",
            name="updated_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="تاریخ بروزرسانی",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="question",
            name="updated_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="تاریخ بروزرسانی"
            ),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="updated_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="تاریخ بروزرسانی"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[
                    apps.core.validators.Validator.phone_number_model_regex_validator
                ],
                verbose_name="Phone Number",
            ),
        ),
    ]
