# Generated by Django 5.1.9 on 2025-06-09 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_questionnairequestion_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ بروزرسانی"
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="Title")),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Weight"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metric",
                        to="core.question",
                        verbose_name="سوال",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question Metric",
                "verbose_name_plural": "Questions Metrics",
            },
        ),
    ]
