# Generated by Django 5.1.9 on 2025-06-10 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_questionmetric"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="questionmetric",
            options={
                "verbose_name": "شاخص سوال",
                "verbose_name_plural": "شاخص\u200cهای سوالات",
            },
        ),
        migrations.AlterField(
            model_name="questionmetric",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metric",
                to="core.questionchoice",
                verbose_name="سوال",
            ),
        ),
    ]
