services:
  web:
    build:
      context: .
      dockerfile: Dockerfile

    command: scripts/server.sh

    ports:
      - "8000:8000"

    volumes:
      - .:/app

    env_file:
      - .env

    environment:
      - CELERY_BROKER_URL=redis://${FARABIN_REDIS_HOST}:${FARABIN_REDIS_PORT}/0 # Connect to the local Redis using environment variables
      - CELERY_RESULT_BACKEND=redis://${FARABIN_REDIS_HOST}:${FARABIN_REDIS_PORT}/0
      - DATABASE_URL=postgres://${FARABIN_DB_USER}:${FARABIN_DB_PASSWORD}@${FARABIN_DB_HOST}:${FARABIN_DB_PORT}/${FARABIN_DB_NAME} # Connect to the local PostgreSQL using environment variables

  celery:
    build:
      context: .
      dockerfile: Dockerfile

    command: scripts/celery_worker.sh

    volumes:
      - .:/app

    env_file:
      - .env

    restart: always

    environment:
      - CELERY_BROKER_URL=redis://${FARABIN_REDIS_HOST}:${FARABIN_REDIS_PORT}/0 # Connect to the local Redis using environment variables
      - CELERY_RESULT_BACKEND=redis://${FARABIN_REDIS_HOST}:${FARABIN_REDIS_PORT}/0
      - DATABASE_URL=postgres://${FARABIN_DB_USER}:${FARABIN_DB_PASSWORD}@${FARABIN_DB_HOST}:${FARABIN_DB_PORT}/${FARABIN_DB_NAME} # Connect to the local PostgreSQL using environment variables

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile

    command: scripts/celery_beat.sh

    volumes:
      - .:/app

    env_file:
      - .env

    restart: always

    environment:
      - CELERY_BROKER_URL=redis://${FARABIN_REDIS_HOST}:${FARABIN_REDIS_PORT}/0 # Connect to the local Redis using environment variables
      - CELERY_RESULT_BACKEND=redis://${FARABIN_REDIS_HOST}:${FARABIN_REDIS_PORT}/0
      - DATABASE_URL=postgres://${FARABIN_DB_USER}:${FARABIN_DB_PASSWORD}@${FARABIN_DB_HOST}:${FARABIN_DB_PORT}/${FARABIN_DB_NAME} # Connect to the local PostgreSQL using environment variables

  flower:
    build:
      context: .
      dockerfile: Dockerfile

    command: scripts/flower.sh

    volumes:
      - .:/app

    env_file:
      - .env

    restart: always

    environment:
      - CELERY_BROKER_URL=redis://${FARABIN_REDIS_HOST}:${FARABIN_REDIS_PORT}/0 # Connect to the local Redis using environment variables
      - CELERY_RESULT_BACKEND=redis://${FARABIN_REDIS_HOST}:${FARABIN_REDIS_PORT}/0
      - DATABASE_URL=postgres://${FARABIN_DB_USER}:${FARABIN_DB_PASSWORD}@${FARABIN_DB_HOST}:${FARABIN_DB_PORT}/${FARABIN_DB_NAME} # Connect to the local PostgreSQL using environment variables

  redis:
    image: redis:latest

    ports:
      - "6379:6379"

    volumes:
      - .:/data
