# Generated by Django 5.1.2 on 2024-10-12 07:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_title', models.CharField(blank=True, choices=[('defend', 'Defend')], default='defend', max_length=50, null=True, verbose_name='Organization Title')),
                ('custom_organization_title', models.CharField(blank=True, help_text='Enter a custom organization title if none of the choices apply.', max_length=50, null=True, verbose_name='Other Organization Title')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_number', models.CharField(max_length=13, unique=True)),
                ('national_code', models.CharField(max_length=20, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostics.province', verbose_name='Province')),
            ],
            options={
                'verbose_name': 'Institute',
                'verbose_name_plural': 'Institutes',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('province', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='diagnostics.province', verbose_name='Province')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('company_title', models.CharField(max_length=255, verbose_name='Company Title')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='EMail')),
                ('social_code', models.CharField(max_length=10, unique=True, verbose_name='Social Code')),
                ('manager_name', models.CharField(max_length=255, verbose_name='Manager Full Name')),
                ('license', models.CharField(choices=[('newbie', 'Newbie'), ('innovative', 'Innovative'), ('technological', 'Technological')], max_length=15, verbose_name='License Type')),
                ('tech_field', models.CharField(blank=True, max_length=500, null=True, verbose_name='Technical Field')),
                ('insurance_list', models.SmallIntegerField(default=1, verbose_name='Insurance List')),
                ('work_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostics.institute', verbose_name='Work Place')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diagnostics.organization', verbose_name='Organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diagnostics.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profiles',
            },
        ),
    ]
