# Generated by Django 5.1.2 on 2024-10-20 08:32

import diagnostics.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organization_province_otp_institute_city'),
        ('diagnostics', '0002_alter_balancereport_balance_report_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institute',
            name='province',
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='work_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.institute', verbose_name='Work Place'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organization', verbose_name='Organization'),
        ),
        migrations.RemoveField(
            model_name='otp',
            name='user',
        ),
        migrations.AlterField(
            model_name='balancereport',
            name='balance_report_file',
            field=models.FileField(blank=True, null=True, upload_to=diagnostics.utils.CustomUtils.rename_folder, verbose_name='Balance Report File'),
        ),
        migrations.AlterField(
            model_name='taxdeclarationfile',
            name='file',
            field=models.FileField(upload_to=diagnostics.utils.CustomUtils.rename_folder, verbose_name='Tax Declaration File'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
        migrations.DeleteModel(
            name='Institute',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
