# Generated by Django 5.1.2 on 2024-10-13 10:03

import diagnostics.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0004_lifecycle_alter_companyprofile_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=0, max_digits=20)),
            ],
        ),
        migrations.AlterField(
            model_name='balancereport',
            name='balance_report_file',
            field=models.FileField(blank=True, null=True, upload_to=diagnostics.utils.CustomUtils.rename_folder, verbose_name='Balance Report File'),
        ),
        migrations.AlterField(
            model_name='taxdeclarationfile',
            name='file',
            field=models.FileField(upload_to=diagnostics.utils.CustomUtils.rename_folder, verbose_name='Tax Declaration File'),
        ),
        migrations.CreateModel(
            name='CompanyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('purchased_date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostics.companyprofile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostics.service')),
            ],
            options={
                'unique_together': {('company', 'service')},
            },
        ),
    ]
