# Generated by Django 5.1.2 on 2024-10-13 10:10

import diagnostics.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0005_service_alter_balancereport_balance_report_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyservice',
            options={'verbose_name': 'Company Service', 'verbose_name_plural': 'Company Services'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterField(
            model_name='balancereport',
            name='balance_report_file',
            field=models.FileField(blank=True, null=True, upload_to=diagnostics.utils.CustomUtils.rename_folder, verbose_name='Balance Report File'),
        ),
        migrations.AlterField(
            model_name='taxdeclarationfile',
            name='file',
            field=models.FileField(upload_to=diagnostics.utils.CustomUtils.rename_folder, verbose_name='Tax Declaration File'),
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostics.companyprofile')),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
            },
        ),
    ]
