# Generated by Django 5.1.2 on 2024-10-21 05:02

import diagnostics.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0011_remove_financialasset_capital_providing_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancereport',
            name='balance_report_file',
            field=models.FileField(blank=True, null=True, upload_to=diagnostics.utils.CustomUtils.rename_folder, verbose_name='Balance Report File'),
        ),
        migrations.AlterField(
            model_name='taxdeclarationfile',
            name='file',
            field=models.FileField(upload_to=diagnostics.utils.CustomUtils.rename_folder, verbose_name='Tax Declaration File'),
        ),
    ]
