# Generated by Django 5.1.2 on 2024-10-21 05:19

import diagnostics.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0015_alter_balancereport_balance_report_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_active',
            field=models.BooleanField(default=False, verbose_name='Service Active'),
        ),
        migrations.AlterField(
            model_name='balancereport',
            name='balance_report_file',
            field=models.FileField(blank=True, null=True, upload_to=diagnostics.utils.CustomUtils.rename_folder, verbose_name='Balance Report File'),
        ),
        migrations.AlterField(
            model_name='taxdeclarationfile',
            name='file',
            field=models.FileField(upload_to=diagnostics.utils.CustomUtils.rename_folder, verbose_name='Tax Declaration File'),
        ),
    ]
