# Generated by Django 5.1.2 on 2024-10-21 05:27

import diagnostics.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_companyservice_service'),
        ('diagnostics', '0016_service_service_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AlterField(
            model_name='balancereport',
            name='balance_report_file',
            field=models.FileField(blank=True, null=True, upload_to=diagnostics.utils.CustomUtils.rename_folder, verbose_name='Balance Report File'),
        ),
        migrations.AlterField(
            model_name='taxdeclarationfile',
            name='file',
            field=models.FileField(upload_to=diagnostics.utils.CustomUtils.rename_folder, verbose_name='Tax Declaration File'),
        ),
    ]
