# Generated by Django 5.1.9 on 2025-07-22 06:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("questionnaire", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Company Title"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "national_code",
                    models.CharField(
                        max_length=11,
                        unique=True,
                        verbose_name="Company National Registration Code",
                    ),
                ),
                (
                    "office_phone_number",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="Invalid_phone_number",
                                message="Phone number must be in 09XXXXXXXXX format.",
                                regex="^0\\d{10}$",
                            )
                        ],
                        verbose_name="Office Phone Number",
                    ),
                ),
                (
                    "insurance_list",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Insurance List Count"
                    ),
                ),
                ("address", models.CharField(max_length=255, verbose_name="Address")),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Is Active?"),
                ),
            ],
            options={
                "verbose_name": "Company Profile",
                "verbose_name_plural": "Company Profiles",
            },
        ),
        migrations.CreateModel(
            name="CompanyQuestionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Submitted At"
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Questionnaire",
                "verbose_name_plural": "Company Questionnaires",
            },
        ),
        migrations.CreateModel(
            name="CompanyService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Activate"),
                ),
                (
                    "purchased_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Purchased At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Service",
                "verbose_name_plural": "Company Services",
            },
        ),
        migrations.CreateModel(
            name="CompanyUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("manager", "Manager"),
                            ("admin", "Admin"),
                            ("staff", "Staff"),
                        ],
                        default="staff",
                        max_length=7,
                        verbose_name="Role",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
            ],
            options={
                "verbose_name": "Company User",
                "verbose_name_plural": "Company Users",
            },
        ),
        migrations.CreateModel(
            name="CompanyUserServicePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("financial", "Financial"),
                            ("management", "Management"),
                            ("mis", "MIS"),
                            ("rad", "R&D"),
                            ("marketing", "Marketing"),
                            ("production", "Production"),
                        ],
                        max_length=10,
                        verbose_name="Service",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
            ],
            options={
                "verbose_name": "Company User Service Permission",
                "verbose_name_plural": "Company User Service Permissions",
            },
        ),
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("itl", "Industrial town"),
                            ("tl", "Technological"),
                            ("kbl", "Knowledge base"),
                            ("ol", "Others"),
                        ],
                        max_length=3,
                        unique=True,
                        verbose_name="License Code",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="License Name")),
            ],
            options={
                "verbose_name": "License",
                "verbose_name_plural": "Licenses",
            },
        ),
        migrations.CreateModel(
            name="LifeCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("operational", "Operational"),
                            ("finance", "Finance"),
                            ("invest", "Invest"),
                        ],
                        default="operational",
                        max_length=11,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Life Cycle",
                "verbose_name_plural": "Life Cycles",
            },
        ),
        migrations.CreateModel(
            name="LifeCycleDecline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Life Cycle Decline",
                "verbose_name_plural": "Life Cycle Declines",
            },
        ),
        migrations.CreateModel(
            name="LifeCycleFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Weight"
                    ),
                ),
            ],
            options={
                "verbose_name": "Life Cycle Feature",
                "verbose_name_plural": "Life Cycle Features",
            },
        ),
        migrations.CreateModel(
            name="LifeCycleFinancialResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("operational", "Operational"),
                            ("finance", "Finance"),
                            ("invest", "Investment"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Life Cycle Financial Resource",
                "verbose_name_plural": "Life Cycle Financial Resources",
            },
        ),
        migrations.CreateModel(
            name="LifeCycleGrowth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Life Cycle Growth",
                "verbose_name_plural": "Life Cycle Growth",
            },
        ),
        migrations.CreateModel(
            name="LifeCycleIntroduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Life Cycle Introduction",
                "verbose_name_plural": "Life Cycle Introduction",
            },
        ),
        migrations.CreateModel(
            name="LifeCycleMaturity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Life Cycle Maturity",
                "verbose_name_plural": "Life Cycle Maturity",
            },
        ),
        migrations.CreateModel(
            name="LifeCycleQuantitative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
            ],
            options={
                "verbose_name": "Life Cycle Quantitative Position",
                "verbose_name_plural": "Life Cycle Quantitative Positions",
            },
        ),
        migrations.CreateModel(
            name="LifeCycleTheoretical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
            ],
            options={
                "verbose_name": "Theoretical Life Cycle Place",
                "verbose_name_plural": "Theoretical Life Cycle Place",
            },
        ),
        migrations.CreateModel(
            name="SpecialTech",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Special Tech",
                "verbose_name_plural": "Special Techs",
            },
        ),
        migrations.CreateModel(
            name="TechField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Tech Field",
                "verbose_name_plural": "Tech Fields",
            },
        ),
        migrations.CreateModel(
            name="CompanyAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answered_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Answered At"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questionnaire.question",
                        verbose_name="Question",
                    ),
                ),
                (
                    "selected_choice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="questionnaire.questionchoice",
                        verbose_name="Selected Choice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Answer",
                "verbose_name_plural": "Company Answers",
            },
        ),
    ]
