# Generated by Django 5.1.10 on 2025-08-20 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
        ("core", "0001_initial"),
        ("packages", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="city",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.city",
                verbose_name="City",
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="province",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.province",
                verbose_name="Province",
            ),
        ),
        migrations.AddField(
            model_name="companyservice",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="company.companyprofile",
                verbose_name="Company",
            ),
        ),
        migrations.AddField(
            model_name="companyservice",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="packages.service",
                verbose_name="Service",
            ),
        ),
        migrations.AddField(
            model_name="companyuser",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_user",
                to="company.companyprofile",
                verbose_name="Company",
            ),
        ),
        migrations.AddField(
            model_name="companyuser",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Company User",
            ),
        ),
        migrations.AddField(
            model_name="companyuserservicepermission",
            name="company_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_permissions",
                to="company.companyuser",
                verbose_name="Company User",
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="license",
            field=models.ManyToManyField(
                to="company.license", verbose_name="License Types"
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="capital_providing_method",
            field=models.ManyToManyField(
                related_name="company_profile",
                to="company.lifecycle",
                verbose_name="Capital Providing Method",
            ),
        ),
        migrations.AddField(
            model_name="lifecyclequantitative",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="company.companyprofile",
                verbose_name="Company",
            ),
        ),
        migrations.AddField(
            model_name="lifecyclequantitative",
            name="resource",
            field=models.ManyToManyField(
                blank=True,
                related_name="life_cycle",
                to="company.lifecyclefinancialresource",
                verbose_name="Resources",
            ),
        ),
        migrations.AddField(
            model_name="lifecycletheoretical",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="company.companyprofile",
                verbose_name="Company",
            ),
        ),
        migrations.AddField(
            model_name="lifecycletheoretical",
            name="decline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="life_cycle",
                to="company.lifecycledecline",
                verbose_name="Decline",
            ),
        ),
        migrations.AddField(
            model_name="lifecycletheoretical",
            name="feature",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="life_cycle",
                to="company.lifecyclefeature",
                verbose_name="Feature",
            ),
        ),
        migrations.AddField(
            model_name="lifecycletheoretical",
            name="growth",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="life_cycle",
                to="company.lifecyclegrowth",
                verbose_name="Growth",
            ),
        ),
        migrations.AddField(
            model_name="lifecycletheoretical",
            name="introduction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="life_cycle",
                to="company.lifecycleintroduction",
                verbose_name="Introduction",
            ),
        ),
        migrations.AddField(
            model_name="lifecycletheoretical",
            name="maturity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="life_cycle",
                to="company.lifecyclematurity",
                verbose_name="Maturity",
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="special_field",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.specialtech",
                verbose_name="Special Field",
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="tech_field",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="company.techfield",
                verbose_name="Technical Field",
            ),
        ),
        migrations.AddConstraint(
            model_name="companyservice",
            constraint=models.UniqueConstraint(
                fields=("company", "service"), name="unique_company_service"
            ),
        ),
        migrations.AddConstraint(
            model_name="companyuser",
            constraint=models.UniqueConstraint(
                fields=("company", "user"), name="unique_user_per_company"
            ),
        ),
        migrations.AddConstraint(
            model_name="companyuser",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "manager")),
                fields=("company",),
                name="unique_manager_per_company",
            ),
        ),
        migrations.AddConstraint(
            model_name="companyuserservicepermission",
            constraint=models.UniqueConstraint(
                fields=("company_user", "service"),
                name="unique_company_user_service_permission",
            ),
        ),
        migrations.AddConstraint(
            model_name="lifecyclequantitative",
            constraint=models.UniqueConstraint(
                fields=("company",), name="unique_company_qunatitative_place"
            ),
        ),
        migrations.AddConstraint(
            model_name="lifecycletheoretical",
            constraint=models.UniqueConstraint(
                fields=("company", "feature"), name="unique_company_theoretical_place"
            ),
        ),
    ]
