# Generated by Django 5.1.10 on 2025-09-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("manager", "Manager"),
                    ("admin", "Admin"),
                    ("staff", "Staff"),
                ],
                default="manager",
                max_length=7,
                verbose_name="Role",
            ),
        ),
    ]
