# Generated by Django 5.1.10 on 2025-09-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_alter_companyuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="ceo_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="CEO Name"
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="ceo_phone_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="CEO Phone Number"
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="establishment_year",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Establishment Year"
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="founding_year",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Founding Year"
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="personnel_count",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Personnel Count"
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="website",
            field=models.URLField(
                blank=True, max_length=255, null=True, verbose_name="Website"
            ),
        ),
    ]
