# Generated by Django 5.1.9 on 2025-05-13 11:16

import django.db.models.deletion
import django_lifecycle.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0005_alter_companyprofile_office_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="LifeCycleDecline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="ویژگی")),
            ],
        ),
        migrations.CreateModel(
            name="LifeCycleFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="ویژگی")),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2, max_digits=2, verbose_name="وزن"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LifeCycleGrowth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="ویژگی")),
            ],
        ),
        migrations.CreateModel(
            name="LifeCycleIntroduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="ویژگی")),
            ],
        ),
        migrations.CreateModel(
            name="LifeCycleMaturity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="ویژگی")),
            ],
        ),
        migrations.CreateModel(
            name="LifeCyclePlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("theorical", "نظری")],
                        max_length=20,
                        unique=True,
                        verbose_name="نوع",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.companyprofile",
                        verbose_name="شرکت",
                    ),
                ),
                (
                    "decline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="life_cycle",
                        to="company.lifecycledecline",
                        verbose_name="افول",
                    ),
                ),
                (
                    "growth",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="life_cycle",
                        to="company.lifecyclegrowth",
                        verbose_name="رشد",
                    ),
                ),
                (
                    "introduction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="life_cycle",
                        to="company.lifecycleintroduction",
                        verbose_name="معرفی",
                    ),
                ),
                (
                    "maturity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="life_cycle",
                        to="company.lifecyclematurity",
                        verbose_name="بلوغ",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="life_cycle",
                        to="company.lifecyclefeature",
                        verbose_name="ویژگی",
                    ),
                ),
            ],
            options={
                "verbose_name": "جایگاه چرخه عمر",
                "verbose_name_plural": "جایگاه چرخه عمر",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "kind"), name="unique_company_kind"
                    )
                ],
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
