# Generated by Django 5.1.9 on 2025-05-13 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0006_lifecycledecline_lifecyclefeature_lifecyclegrowth_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lifecycledecline",
            options={
                "verbose_name": "چرخه عمر افول",
                "verbose_name_plural": "چرخه عمر افول",
            },
        ),
        migrations.AlterModelOptions(
            name="lifecyclefeature",
            options={
                "verbose_name": "ویژگی\u200c چرخه عمر",
                "verbose_name_plural": "ویژگی\u200cهای چرخه عمر",
            },
        ),
        migrations.AlterModelOptions(
            name="lifecyclegrowth",
            options={
                "verbose_name": "چرخه عمر رشد",
                "verbose_name_plural": "چرخه عمر رشد",
            },
        ),
        migrations.AlterModelOptions(
            name="lifecycleintroduction",
            options={
                "verbose_name": "چرخه عمر معرفی",
                "verbose_name_plural": "چرخه عمر معرفی",
            },
        ),
        migrations.AlterModelOptions(
            name="lifecyclematurity",
            options={
                "verbose_name": "چرخه عمر بلوغ",
                "verbose_name_plural": "چرخه عمر بلوغ",
            },
        ),
        migrations.RemoveConstraint(
            model_name="lifecycleplace",
            name="unique_company_kind",
        ),
    ]
