# Generated by Django 5.1.9 on 2025-05-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0007_alter_lifecycledecline_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lifecyclefeature",
            name="weight",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="وزن"
            ),
        ),
    ]
