# Generated by Django 5.1.9 on 2025-05-13 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0008_alter_lifecyclefeature_weight"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lifecyclefeature",
            options={
                "verbose_name": "چرخه عمر ویژگی\u200c",
                "verbose_name_plural": "چرخه عمر ویژگی\u200cها",
            },
        ),
        migrations.AlterModelOptions(
            name="lifecycleplace",
            options={
                "verbose_name": "چرخه عمر جایگاه",
                "verbose_name_plural": "چرخه عمر جایگاه",
            },
        ),
    ]
