# Generated by Django 5.1.9 on 2025-05-13 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0009_alter_lifecyclefeature_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lifecycleplace",
            name="kind",
            field=models.CharField(
                choices=[("theorical", "نظری")], max_length=20, verbose_name="نوع"
            ),
        ),
        migrations.AlterField(
            model_name="lifecycleplace",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="life_cycle",
                to="company.lifecyclefeature",
                unique=True,
                verbose_name="ویژگی",
            ),
        ),
    ]
