# Generated by Django 5.1.9 on 2025-05-13 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0010_alter_lifecycleplace_kind_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lifecycleplace",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="life_cycle",
                to="company.lifecyclefeature",
                verbose_name="ویژگی",
            ),
        ),
    ]
