# Generated by Django 5.1.9 on 2025-05-13 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0012_remove_lifecycleplace_property_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lifecycleplace",
            name="property",
        ),
        migrations.AddField(
            model_name="lifecycleplace",
            name="property",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="life_cycle",
                to="company.lifecyclefeature",
                verbose_name="ویژگی",
            ),
            preserve_default=False,
        ),
    ]
