# Generated by Django 5.1.9 on 2025-05-14 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0013_remove_lifecycleplace_property_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lifecycleplace",
            old_name="property",
            new_name="feature",
        ),
    ]
