# Generated by Django 5.1.9 on 2025-05-14 14:52

import django.db.models.deletion
import django_lifecycle.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0014_rename_property_lifecycleplace_feature"),
    ]

    operations = [
        migrations.CreateModel(
            name="LifeCycleTheoritical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.companyprofile",
                        verbose_name="شرکت",
                    ),
                ),
                (
                    "decline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="life_cycle",
                        to="company.lifecycledecline",
                        verbose_name="افول",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="life_cycle",
                        to="company.lifecyclefeature",
                        verbose_name="ویژگی",
                    ),
                ),
                (
                    "growth",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="life_cycle",
                        to="company.lifecyclegrowth",
                        verbose_name="رشد",
                    ),
                ),
                (
                    "introduction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="life_cycle",
                        to="company.lifecycleintroduction",
                        verbose_name="معرفی",
                    ),
                ),
                (
                    "maturity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="life_cycle",
                        to="company.lifecyclematurity",
                        verbose_name="بلوغ",
                    ),
                ),
            ],
            options={
                "verbose_name": "چرخه عمر جایگاه",
                "verbose_name_plural": "چرخه عمر جایگاه",
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.DeleteModel(
            name="LifeCyclePlace",
        ),
    ]
