# Generated by Django 5.1.9 on 2025-05-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0018_rename_lifecycletheoritical_lifecycletheoretical"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="lifecyclequantitative",
            constraint=models.UniqueConstraint(
                fields=("company",), name="unique_company_qunatitative_place"
            ),
        ),
    ]
