# Generated by Django 5.1.9 on 2025-05-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0019_lifecyclequantitative_unique_company_qunatitative_place"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="lifecycletheoretical",
            constraint=models.UniqueConstraint(
                fields=("company", "feature"), name="unique_company_theoretical_place"
            ),
        ),
    ]
