# Generated by Django 5.1.9 on 2025-06-09 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0021_companyquestionnaire_companyanswer"),
        ("core", "0007_alter_question_options_alter_questionchoice_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="companyanswer",
            options={
                "verbose_name": "پاسخ شرکت",
                "verbose_name_plural": "پاسخ\u200cهای شرکت\u200cها",
            },
        ),
        migrations.AlterModelOptions(
            name="companyquestionnaire",
            options={
                "verbose_name": "پرسشنامه شرکت",
                "verbose_name_plural": "پرسشنامه\u200cهای شرکت\u200cها",
            },
        ),
        migrations.AlterField(
            model_name="companyanswer",
            name="answered_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ پاسخ"),
        ),
        migrations.AlterField(
            model_name="companyanswer",
            name="company_questionnaire",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="company.companyquestionnaire",
                verbose_name="پرسشنامه\u200c شرکت",
            ),
        ),
        migrations.AlterField(
            model_name="companyanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.question",
                verbose_name="سوال",
            ),
        ),
        migrations.AlterField(
            model_name="companyanswer",
            name="selected_choice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.questionchoice",
                verbose_name="گزینه انتخابی",
            ),
        ),
        migrations.AlterField(
            model_name="companyquestionnaire",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="company.companyprofile",
                verbose_name="شرکت",
            ),
        ),
        migrations.AlterField(
            model_name="companyquestionnaire",
            name="questionnaire",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.questionnaire",
                verbose_name="پرسشنامه",
            ),
        ),
        migrations.AlterField(
            model_name="companyquestionnaire",
            name="submitted_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت"),
        ),
    ]
