# Generated by Django 5.1.9 on 2025-06-09 04:43

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0022_alter_companyanswer_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="manager_phone_number",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                unique=True,
                validators=[
                    apps.core.validators.Validator.phone_number_model_regex_validator
                ],
                verbose_name="Manager Phone Number",
            ),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="office_phone_number",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                unique=True,
                validators=[
                    apps.core.validators.Validator.landline_number_model_regex_validator
                ],
                verbose_name="Office Phone Number",
            ),
        ),
    ]
