# Generated by Django 5.1.10 on 2025-09-15 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("balancesheet", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="balancesheet",
            options={
                "ordering": ["company", "-year"],
                "verbose_name": "ترازنامه",
                "verbose_name_plural": "ترازنامه ها",
            },
        ),
        migrations.AlterModelOptions(
            name="contingentaccount",
            options={
                "verbose_name": " حساب انتظامی",
                "verbose_name_plural": " حساب\u200cهای انتظامی",
            },
        ),
        migrations.AlterModelOptions(
            name="currentasset",
            options={
                "verbose_name": "دارایی\u200c جاری",
                "verbose_name_plural": "دارایی\u200cهای جاری",
            },
        ),
        migrations.AlterModelOptions(
            name="currentliability",
            options={
                "verbose_name": "بدهی\u200c جاری",
                "verbose_name_plural": "بدهی\u200cهای جاری",
            },
        ),
        migrations.AlterModelOptions(
            name="equity",
            options={
                "verbose_name": "حقوق صاحبان سهام",
                "verbose_name_plural": "حقوق صاحبان سهام",
            },
        ),
        migrations.AlterModelOptions(
            name="expense",
            options={"verbose_name": "هزینه ", "verbose_name_plural": "هزینه ها"},
        ),
        migrations.AlterModelOptions(
            name="fixedasset",
            options={
                "verbose_name": "دارایی غیر جاری ",
                "verbose_name_plural": "دارایی های غیر جاری ا",
            },
        ),
        migrations.AlterModelOptions(
            name="longtermliability",
            options={
                "verbose_name": "بدهی\u200c بلندمدت",
                "verbose_name_plural": "بدهی\u200cهای بلندمدت",
            },
        ),
        migrations.AlterModelOptions(
            name="revenue",
            options={"verbose_name": "درآمد", "verbose_name_plural": "درآمدها"},
        ),
    ]
