# Generated by Django 5.1.10 on 2025-09-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "balancesheet",
            "0003_alter_cash_options_alter_contingentaccount_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cash",
            options={
                "verbose_name": "موجودی نقد  - [ 11 ] ",
                "verbose_name_plural": "کل موجودی نقد  - [ 11 ] ",
            },
        ),
        migrations.AlterModelOptions(
            name="currentasset",
            options={
                "verbose_name": " دارایی\u200c جاری - [ 1 ]",
                "verbose_name_plural": " کل دارایی\u200cهای جاری  - [ 1 ]",
            },
        ),
        migrations.AlterModelOptions(
            name="currentliability",
            options={
                "verbose_name": "بدهی\u200c جاری - [ 3 ]",
                "verbose_name_plural": "کل بدهی\u200cهای جاری  - [ 3 ]",
            },
        ),
        migrations.AlterModelOptions(
            name="equity",
            options={
                "verbose_name": "حقوق صاحبان سهام  - [ 5 ]",
                "verbose_name_plural": " کل حقوق صاحبان سهام  - [ 5 ]",
            },
        ),
        migrations.AlterModelOptions(
            name="fixedasset",
            options={
                "verbose_name": "دارایی غیر جاری  - [ 2 ]",
                "verbose_name_plural": "کل دارایی های غیر جاری - [ 2 ]",
            },
        ),
        migrations.AlterModelOptions(
            name="longtermliability",
            options={
                "verbose_name": " بدهی\u200c بلندمدت  - [ 4 ]",
                "verbose_name_plural": " کل بدهی\u200cهای بلندمدت  - [ 4 ]",
            },
        ),
        migrations.AlterModelOptions(
            name="revenue",
            options={
                "verbose_name": " درآمد  - [ 6 ]",
                "verbose_name_plural": " کل درآمدها - [ 6 ]",
            },
        ),
    ]
