# Generated by Django 5.1.10 on 2025-09-15 13:00

import apps.balancesheet.models.current_asset
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balancesheet", "0004_alter_cash_options_alter_currentasset_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assetsheldforsale",
            options={
                "verbose_name": " دارایی نگهداری شده برای فروش - [ 18 ]",
                "verbose_name_plural": " کل دارایی نگهداری شده برای فروش  - [ 18 ]",
            },
        ),
        migrations.AlterModelOptions(
            name="inventory",
            options={
                "verbose_name": " موجودی مواد و کالا - [ 16 ]",
                "verbose_name_plural": " کل موجودی مواد و کالا  - [ 16 ]",
            },
        ),
        migrations.AlterModelOptions(
            name="nontradereceivable",
            options={
                "verbose_name": " حساب\u200cها و اسناد دریافتنی غیرتجاری - [ 14 ]",
                "verbose_name_plural": " کل حساب\u200cها و اسناد دریافتنی غیرتجاری  - [ 14 ]",
            },
        ),
        migrations.AlterModelOptions(
            name="ordersandprepayments",
            options={
                "verbose_name": " سفارش\u200cها و پیش\u200cپرداخت\u200cها - [ 17 ]",
                "verbose_name_plural": " کل سفارش\u200cها و پیش\u200cپرداخت\u200cها  - [ 17 ]",
            },
        ),
        migrations.AlterModelOptions(
            name="shareholderreceivable",
            options={
                "verbose_name": " جاری شرکا/سهامداران - [ 15 ]",
                "verbose_name_plural": " کل جاری شرکا/سهامداران  - [ 15 ]",
            },
        ),
        migrations.AlterModelOptions(
            name="shortterminvestment",
            options={
                "verbose_name": " سرمایه\u200cگذاری\u200cهای کوتاه\u200cمدت - [ 12 ]",
                "verbose_name_plural": " کل سرمایه\u200cگذاری\u200cهای کوتاه\u200cمدت  - [ 12 ]",
            },
        ),
        migrations.AlterModelOptions(
            name="tradereceivable",
            options={
                "verbose_name": " حساب\u200cها و اسناد دریافتنی تجاری - [ 13 ]",
                "verbose_name_plural": " کل حساب\u200cها و اسناد دریافتنی تجاری  - [ 13 ]",
            },
        ),
        migrations.AlterField(
            model_name="assetsheldforsale",
            name="assets_held_for_sale",
            field=models.JSONField(
                default=apps.balancesheet.models.current_asset.default_debit,
                verbose_name="[ 1801 ]ارزش دارایی نگهداری شده برای فروش",
            ),
        ),
        migrations.AlterField(
            model_name="assetsheldforsale",
            name="impairment_reserve",
            field=models.JSONField(
                default=apps.balancesheet.models.current_asset.default_credit,
                verbose_name="[ 1802 ]ذخیره کاهش ارزش دارایی",
            ),
        ),
        migrations.AlterField(
            model_name="cash",
            name="bank_balances",
            field=models.JSONField(
                default=apps.balancesheet.models.current_asset.default_debit,
                verbose_name="[ 1102 ] بانک\u200cها",
            ),
        ),
        migrations.AlterField(
            model_name="cash",
            name="cash_in_hand",
            field=models.JSONField(
                default=apps.balancesheet.models.current_asset.default_debit,
                verbose_name=" [ 1101 ] صندوق",
            ),
        ),
        migrations.AlterField(
            model_name="cash",
            name="cash_in_transit",
            field=models.JSONField(
                default=apps.balancesheet.models.current_asset.default_debit,
                verbose_name="[ 1104 ] وجوه در راه",
            ),
        ),
        migrations.AlterField(
            model_name="cash",
            name="petty_cash",
            field=models.JSONField(
                default=apps.balancesheet.models.current_asset.default_debit,
                verbose_name="[ 1103 ] تنخواه\u200cگردان\u200cها",
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="finished_goods",
            field=models.JSONField(
                default=apps.balancesheet.models.current_asset.default_debit,
                verbose_name="[ 1603 ]موجودی کالای ساخته شده و آماده فروش",
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="idle_items",
            field=models.JSONField(
                default=apps.balancesheet.models.current_asset.default_debit,
                verbose_name="[ 1607 ]موجودی اقلام راکد",
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="inventory_impairment",
            field=models.JSONField(
                default=apps.balancesheet.models.current_asset.default_credit,
                verbose_name="[ 1609 ]ذخیره کاهش ارزش موجودی",
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="packaging_materials",
            field=models.JSONField(
                default=apps.balancesheet.models.current_asset.default_debit,
                verbose_name="[ 1606 ]موجود مواد بسته بندی",
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="purchased_goods_for_sale",
            field=models.JSONField(
                default=apps.balancesheet.models.current_asset.default_debit,
                verbose_name="[ 1604 ]موجودی کالای خریداری شده جهت فروش",
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="raw_materials",
            field=models.JSONField(
                default=apps.balancesheet.models.current_asset.default_debit,
                verbose_name="[ 1601 ]موجودی مواد اولیه",
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="scrap_raw_materials",
            field=models.JSONField(
                default=apps.balancesheet.models.current_asset.default_debit,
                verbose_name="[ 1608 ]موجودی ضایعات مواد اولیه",
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="spare_parts",
            field=models.JSONField(
                default=apps.balancesheet.models.current_asset.default_debit,
                verbose_name="[ 1605 ]موجودی قطعات و لوازم یدکی",
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="work_in_progress",
            field=models.JSONField(
                default=apps.balancesheet.models.current_asset.default_debit,
                verbose_name="[ 1602 ]موجودی کالای درجریان ساخت",
            ),
        ),
        migrations.AlterField(
            model_name="nontradereceivable",
            name="deposits_with_others",
            field=models.JSONField(
                default=apps.balancesheet.models.current_asset.default_debit,
                verbose_name="[ 1407 ]سپرده\u200cهای ما نزد دیگران",
            ),
        ),
        migrations.AlterField(
            model_name="nontradereceivable",
            name="director_receivables",
            field=models.JSONField(
                default=apps.balancesheet.models.current_asset.default_debit,
                verbose_name="[ 1404 ]حساب\u200cهای دریافتنی از مدیران و اعضای هیات مدیره",
            ),
        ),
        migrations.AlterField(
            model_name="nontradereceivable",
            name="dividends_receivable",
            field=models.JSONField(
                default=apps.balancesheet.models.current_asset.default_debit,
                verbose_name="[ 1408 ]سود سهام دریافتنی",
            ),
        ),
        migrations.AlterField(
            model_name="nontradereceivable",
            name="employee_receivables",
            field=models.JSONField(
                default=apps.balancesheet.models.current_asset.default_debit,
                verbose_name="[ 1403 ]حساب\u200cهای دریافتنی از کارکنان (وام و مساعده)",
            ),
        ),
        migrations.AlterField(
            model_name="nontradereceivable",
            name="non_trade_accounts_receivable",
            field=models.JSONField(
                default=apps.balancesheet.models.current_asset.default_debit,
                verbose_name="[ 1401 ]حساب\u200cهای دریافتنی غیرتجاری",
            ),
        ),
        migrations.AlterField(
            model_name="nontradereceivable",
            name="non_trade_notes_receivable",
            field=models.JSONField(
                default=apps.balancesheet.models.current_asset.default_debit,
                verbose_name="[ 1402 ]اسناد دریافتنی غیرتجاری",
            ),
        ),
        migrations.AlterField(
            model_name="nontradereceivable",
            name="related_companies_receivables",
            field=models.JSONField(
                default=apps.balancesheet.models.current_asset.default_debit,
                verbose_name="[ 1405 ]حساب\u200cهای دریافتنی از شرکت\u200cها و اشخاص وابسته",
            ),
        ),
        migrations.AlterField(
            model_name="nontradereceivable",
            name="vat_receivable",
            field=models.JSONField(
                default=apps.balancesheet.models.current_asset.default_debit,
                verbose_name="[ 1406 ]مالیات بر ارزش افزوده",
            ),
        ),
        migrations.AlterField(
            model_name="ordersandprepayments",
            name="orders_in_transit",
            field=models.JSONField(
                default=apps.balancesheet.models.current_asset.default_debit,
                verbose_name="[ 1705 ]سفارشات در راه",
            ),
        ),
        migrations.AlterField(
            model_name="ordersandprepayments",
            name="other_prepayments",
            field=models.JSONField(
                default=apps.balancesheet.models.current_asset.default_debit,
                verbose_name="[ 1708 ]سایر پیش\u200cپرداخت\u200cها",
            ),
        ),
        migrations.AlterField(
            model_name="ordersandprepayments",
            name="prepaid_goods_and_services",
            field=models.JSONField(
                default=apps.balancesheet.models.current_asset.default_debit,
                verbose_name="[ 1701 ]پیش\u200cپرداخت خرید کالا و خدمات",
            ),
        ),
        migrations.AlterField(
            model_name="ordersandprepayments",
            name="prepaid_income_tax",
            field=models.JSONField(
                default=apps.balancesheet.models.current_asset.default_debit,
                verbose_name="[ 1702 ]پیش\u200cپرداخت مالیات عملکرد",
            ),
        ),
        migrations.AlterField(
            model_name="ordersandprepayments",
            name="prepaid_insurance",
            field=models.JSONField(
                default=apps.balancesheet.models.current_asset.default_debit,
                verbose_name="[ 1704 ]پیش\u200cپرداخت بیمه",
            ),
        ),
        migrations.AlterField(
            model_name="ordersandprepayments",
            name="prepaid_interest_on_loans",
            field=models.JSONField(
                default=apps.balancesheet.models.current_asset.default_debit,
                verbose_name="[ 1707 ]پیش پرداخت سود تسهیلات",
            ),
        ),
        migrations.AlterField(
            model_name="ordersandprepayments",
            name="prepaid_loans",
            field=models.JSONField(
                default=apps.balancesheet.models.current_asset.default_debit,
                verbose_name="[ 1706 ]پیش پرداخت تسهیلات",
            ),
        ),
        migrations.AlterField(
            model_name="ordersandprepayments",
            name="prepaid_rent",
            field=models.JSONField(
                default=apps.balancesheet.models.current_asset.default_debit,
                verbose_name="[ 1703 ]پیش\u200cپرداخت اجاره",
            ),
        ),
        migrations.AlterField(
            model_name="shareholderreceivable",
            name="amount",
            field=models.JSONField(
                default=apps.balancesheet.models.current_asset.default_debit,
                verbose_name="[ 1501 ]مبلغ",
            ),
        ),
        migrations.AlterField(
            model_name="shortterminvestment",
            name="etf_investment_fund",
            field=models.JSONField(
                default=apps.balancesheet.models.current_asset.default_debit,
                verbose_name="[ 1204 ]صندوق سرمایه گذاری قابل معامله (ETF)",
            ),
        ),
        migrations.AlterField(
            model_name="shortterminvestment",
            name="other_short_term_investments",
            field=models.JSONField(
                default=apps.balancesheet.models.current_asset.default_debit,
                verbose_name="[ 1205 ]سایر سرمایه گذاری\u200cهای کوتاه\u200cمدت",
            ),
        ),
        migrations.AlterField(
            model_name="shortterminvestment",
            name="participation_bonds",
            field=models.JSONField(
                default=apps.balancesheet.models.current_asset.default_debit,
                verbose_name="[ 1203 ]اوراق مشارکت",
            ),
        ),
        migrations.AlterField(
            model_name="shortterminvestment",
            name="short_term_deposits",
            field=models.JSONField(
                default=apps.balancesheet.models.current_asset.default_debit,
                verbose_name="سپرده\u200cهای کوتاه مدت [ 1201 ] ",
            ),
        ),
        migrations.AlterField(
            model_name="shortterminvestment",
            name="short_term_investment_impairment",
            field=models.JSONField(
                default=apps.balancesheet.models.current_asset.default_credit,
                verbose_name="[ 1206 ]ذخیره\u200cی کاهش ارزش سرمایه\u200cگذاری\u200cهای کوتاه\u200cمدت",
            ),
        ),
        migrations.AlterField(
            model_name="shortterminvestment",
            name="tradable_stocks",
            field=models.JSONField(
                default=apps.balancesheet.models.current_asset.default_debit,
                verbose_name="سهام بورسی قابل معامله[ 1202 ]",
            ),
        ),
        migrations.AlterField(
            model_name="tradereceivable",
            name="doubtful_receivables_provision",
            field=models.JSONField(
                default=apps.balancesheet.models.current_asset.default_debit,
                verbose_name="[ 1306 ]ذخیره\u200cی مطالبات مشکوک\u200cالوصول",
            ),
        ),
        migrations.AlterField(
            model_name="tradereceivable",
            name="notes_in_collection",
            field=models.JSONField(
                default=apps.balancesheet.models.current_asset.default_debit,
                verbose_name="[ 1304 ]اسناد درجریان وصول",
            ),
        ),
        migrations.AlterField(
            model_name="tradereceivable",
            name="receivables_in_litigation",
            field=models.JSONField(
                default=apps.balancesheet.models.current_asset.default_debit,
                verbose_name="[ 1303 ]حساب\u200cهای دریافتنی در دعاوی حقوقی",
            ),
        ),
        migrations.AlterField(
            model_name="tradereceivable",
            name="returned_cheques",
            field=models.JSONField(
                default=apps.balancesheet.models.current_asset.default_debit,
                verbose_name="[ 1305 ]اسناد دریافتنی واخواستی (چک\u200cهای برگشتی مشتری)",
            ),
        ),
        migrations.AlterField(
            model_name="tradereceivable",
            name="trade_accounts_receivable",
            field=models.JSONField(
                default=apps.balancesheet.models.current_asset.default_debit,
                verbose_name="[ 1301 ]حساب\u200cهای دریافتنی تجاری",
            ),
        ),
        migrations.AlterField(
            model_name="tradereceivable",
            name="trade_notes_receivable",
            field=models.JSONField(
                default=apps.balancesheet.models.current_asset.default_debit,
                verbose_name="[ 1302 ]اسناد دریافتنی تجاری",
            ),
        ),
    ]
