# Generated by Django 5.1.10 on 2025-09-16 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("balancesheet", "0005_alter_assetsheldforsale_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="advancesanddeposits",
            options={
                "verbose_name": "پیش\u200cدریافت\u200cها و سپرده\u200cها - [ 35 ]",
                "verbose_name_plural": "کل پیش\u200cدریافت\u200cها و سپرده\u200cها  - [ 35 ] ",
            },
        ),
        migrations.AlterModelOptions(
            name="assetsinprogress",
            options={
                "verbose_name": "دارایی در جریان تکمیل  - [ 22 ]",
                "verbose_name_plural": "دارایی در جریان تکمیل - [ 22 ]",
            },
        ),
        migrations.AlterModelOptions(
            name="capitalincreasedecrease",
            options={
                "verbose_name": "افزایش /کاهش سرمایه  - [ 52 ]",
                "verbose_name_plural": " کل افزایش /کاهش سرمایه  - [ 52 ]",
            },
        ),
        migrations.AlterModelOptions(
            name="contingentaccounts",
            options={
                "verbose_name": " حساب\u200cهای انتظامی  - [ 81 ]",
                "verbose_name_plural": " کل حساب\u200cهای انتظامی  - [ 81 ]",
            },
        ),
        migrations.AlterModelOptions(
            name="contingentcounterparties",
            options={
                "verbose_name": " طرف حساب\u200cهای انتظامی  - [ 82 ]",
                "verbose_name_plural": " کل طرف حساب\u200cهای انتظامی - [ 82 ]",
            },
        ),
        migrations.AlterModelOptions(
            name="distributionandmarketingcosts",
            options={
                "verbose_name": " هزینه\u200cهای توزیع و فروش و بازاریابی  - [ 72 ]",
                "verbose_name_plural": " کل هزینه\u200cهای توزیع و فروش و بازاریابی  - [ 72 ]",
            },
        ),
        migrations.AlterModelOptions(
            name="dividendspayable",
            options={
                "verbose_name": "سود سهام پرداختنی - [ 33 ]",
                "verbose_name_plural": "کل سود سهام پرداختنی  - [ 33 ] ",
            },
        ),
        migrations.AlterModelOptions(
            name="financialcosts",
            options={
                "verbose_name": " هزینه\u200cهای مالی  - [ 74 ]",
                "verbose_name_plural": " کل هزینه\u200cهای مالی   - [ 74 ]",
            },
        ),
        migrations.AlterModelOptions(
            name="foreigncurrencyrevenue",
            options={
                "verbose_name": " درآمد تسعیر ارز  - [ 63 ]",
                "verbose_name_plural": " کل درآمد تسعیر ارز - [ 63 ]",
            },
        ),
        migrations.AlterModelOptions(
            name="foreigncurrencytranslationdifference",
            options={
                "verbose_name": "تفاوت تسعیر ارز  - [ 58 ]",
                "verbose_name_plural": " کل تفاوت تسعیر ارز  - [ 58 ]",
            },
        ),
        migrations.AlterModelOptions(
            name="generalandadministrativecosts",
            options={
                "verbose_name": " هزینه های عمومی و اداری  - [ 73 ]",
                "verbose_name_plural": " کل هزینه های عمومی و اداری - [ 73 ]",
            },
        ),
        migrations.AlterModelOptions(
            name="initialcapital",
            options={
                "verbose_name": "سرمایه اولیه - [ 51 ]",
                "verbose_name_plural": " کل سرمایه اولیه - [ 51 ]",
            },
        ),
        migrations.AlterModelOptions(
            name="intangibleasset",
            options={
                "verbose_name": "دارایی\u200cهای نامشهود  - [ 20 ]",
                "verbose_name_plural": "کل دارایی\u200cهای نامشهود - [ 20 ]",
            },
        ),
        migrations.AlterModelOptions(
            name="legalreserve",
            options={
                "verbose_name": "اندوخته\u200cی قانونی  - [ 55 ]",
                "verbose_name_plural": " کل اندوخته\u200cی قانونی  - [ 55 ]",
            },
        ),
        migrations.AlterModelOptions(
            name="liabilitiesrelatedtoassetsheldforsale",
            options={
                "verbose_name": "بدهی\u200cهای مرتبط با دارایی\u200cهای نگهداری\u200cشده برای فروش - [ 36 ]",
                "verbose_name_plural": "کل بدهی\u200cهای مرتبط با دارایی\u200cهای نگهداری\u200cشده برای فروشا  - [ 36 ] ",
            },
        ),
        migrations.AlterModelOptions(
            name="longtermaccountspayable",
            options={
                "verbose_name": " حساب ها و اسناد پرداختنی بلندمدت  - [ 40 ]",
                "verbose_name_plural": " کل حساب ها و اسناد پرداختنی بلندمدت  - [ 40 ]",
            },
        ),
        migrations.AlterModelOptions(
            name="longterminvestment",
            options={
                "verbose_name": "سرمایه\u200cگذاری بلندمدت  - [ 23 ]",
                "verbose_name_plural": "کل سرمایه\u200cگذاری بلندمدت - [ 23 ]",
            },
        ),
        migrations.AlterModelOptions(
            name="longtermloans",
            options={
                "verbose_name": " تسهیلات مالی دریافتی بلندمدت از بانک\u200cها  - [ 41 ]",
                "verbose_name_plural": " کل تسهیلات مالی دریافتی بلندمدت از بانک\u200cها - [ 41 ]",
            },
        ),
        migrations.AlterModelOptions(
            name="longtermprovisions",
            options={
                "verbose_name": " ذخایر بلند مدت  - [ 42 ]",
                "verbose_name_plural": " کل ذخایر بلند مدت  - [ 42 ]",
            },
        ),
        migrations.AlterModelOptions(
            name="netsales",
            options={
                "verbose_name": " خالص فروش  - [ 61 ]",
                "verbose_name_plural": " کل خالص فروش - [ 61 ]",
            },
        ),
        migrations.AlterModelOptions(
            name="nontradeaccountspayable",
            options={
                "verbose_name": "حساب\u200cها و اسناد پرداختنی غیرتجاری - [ 31 ]",
                "verbose_name_plural": "کل حساب\u200cها و اسناد پرداختنی غیرتجاری  - [ 31 ]",
            },
        ),
        migrations.AlterModelOptions(
            name="othernoncurrentasset",
            options={
                "verbose_name": "سایر دارایی های غیر جاری  - [ 24 ]",
                "verbose_name_plural": "کل سایر دارایی های غیر جاری - [ 24 ]",
            },
        ),
        migrations.AlterModelOptions(
            name="otheroperatingcosts",
            options={
                "verbose_name": " سایر هزینه های عملیاتی  - [ 75 ]",
                "verbose_name_plural": " کل سایر هزینه های عملیاتی  - [ 75 ]",
            },
        ),
        migrations.AlterModelOptions(
            name="otheroperatingrevenue",
            options={
                "verbose_name": " سایر درآمدهای عملیاتی  - [ 64 ]",
                "verbose_name_plural": " کل سایر درآمدهای عملیاتی - [ 64 ]",
            },
        ),
        migrations.AlterModelOptions(
            name="otherreserves",
            options={
                "verbose_name": "سایر اندوخته\u200cها  - [ 56 ]",
                "verbose_name_plural": " کل سایر اندوخته\u200cها  - [ 56 ]",
            },
        ),
        migrations.AlterModelOptions(
            name="productioncosts",
            options={
                "verbose_name": " هزینه های تولید  - [ 71 ]",
                "verbose_name_plural": " کل هزینه های تولید  - [ 71 ]",
            },
        ),
        migrations.AlterModelOptions(
            name="retainedearnings",
            options={
                "verbose_name": "سود (زیان)انباشته  - [ 59 ]",
                "verbose_name_plural": " کل سود (زیان)انباشته  - [ 59 ]",
            },
        ),
        migrations.AlterModelOptions(
            name="revaluationsurplus",
            options={
                "verbose_name": "مازاد تجدید ارزیابی دارایی\u200cها  - [ 57 ]",
                "verbose_name_plural": " کل مازاد تجدید ارزیابی دارایی\u200cها  - [ 57 ]",
            },
        ),
        migrations.AlterModelOptions(
            name="servicerevenue",
            options={
                "verbose_name": " درآمد ارائه خدمات  - [ 62 ]",
                "verbose_name_plural": " کل درآمد ارائه خدمات - [ 62 ]",
            },
        ),
        migrations.AlterModelOptions(
            name="sharediscountreserve",
            options={
                "verbose_name": "اندوخته کسر سهام  - [ 54 ]",
                "verbose_name_plural": " کل اندوخته کسر سهام - [ 54 ]",
            },
        ),
        migrations.AlterModelOptions(
            name="shareholderpayables",
            options={
                "verbose_name": "جاری شرکا/سهامداران - [ 32 ]",
                "verbose_name_plural": "کل جاری شرکا/سهامداران  - [ 32 ]",
            },
        ),
        migrations.AlterModelOptions(
            name="sharepremiumreserve",
            options={
                "verbose_name": "اندوخته\u200cی صرف سهام  - [ 53 ]",
                "verbose_name_plural": " کل اندوخته\u200cی صرف سهام - [ 53 ]",
            },
        ),
        migrations.AlterModelOptions(
            name="shorttermloans",
            options={
                "verbose_name": "تسهیلات مالی دریافتی کوتاه\u200cمدت - [ 34 ]",
                "verbose_name_plural": "کل تسهیلات مالی دریافتی کوتاه\u200cمدت  - [ 34 ] ",
            },
        ),
        migrations.AlterModelOptions(
            name="tangiblefixedasset",
            options={
                "verbose_name": "دارایی\u200cهای ثابت مشهود  - [ 21 ]",
                "verbose_name_plural": "کل دارایی\u200cهای ثابت مشهود - [ 21 ]",
            },
        ),
        migrations.AlterModelOptions(
            name="taxpayable",
            options={
                "verbose_name": "مالیات پرداختنی - [ 38 ]",
                "verbose_name_plural": "کل مالیات پرداختنی  - [ 38 ] ",
            },
        ),
        migrations.AlterModelOptions(
            name="taxprovision",
            options={
                "verbose_name": "ذخیره مالیات - [ 37 ]",
                "verbose_name_plural": "کل ذخیره مالیات  - [ 37 ] ",
            },
        ),
        migrations.AlterModelOptions(
            name="tradeaccountspayable",
            options={
                "verbose_name": "حساب ها و اسناد پرداختنی تجاری - [ 30 ]",
                "verbose_name_plural": "کل حساب ها و اسناد پرداختنی تجاری  - [ 30 ]",
            },
        ),
    ]
