# Generated by Django 5.1.10 on 2025-09-21 08:40

import apps.balancesheet.models.balance_sheet
import constants.validators.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balancesheet", "0007_alter_advancesanddeposits_current_liability_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="balancesheet",
            name="excel_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.balancesheet.models.balance_sheet.get_bs_file_upload_path,
                validators=[
                    constants.validators.validators.Validator.excel_file_validator
                ],
                verbose_name="فایل اکسل",
            ),
        ),
    ]
