# Generated by Django 5.1.2 on 2024-10-20 15:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_title', models.CharField(max_length=255, verbose_name='Company Title')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('social_code', models.CharField(max_length=10, unique=True, verbose_name='Social Code')),
                ('manager_name', models.CharField(max_length=255, verbose_name='Manager Full Name')),
                ('license', models.CharField(choices=[('newbie', 'Newbie'), ('innovative', 'Innovative'), ('technological', 'Technological')], max_length=15, verbose_name='License Type')),
                ('tech_field', models.CharField(blank=True, max_length=500, null=True, verbose_name='Technical Field')),
                ('insurance_list', models.PositiveSmallIntegerField(default=1, verbose_name='Insurance List')),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profiles',
            },
        ),
        migrations.CreateModel(
            name='CompanyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activate')),
                ('purchased_date', models.DateTimeField(auto_now_add=True, verbose_name='Purchased Date')),
            ],
            options={
                'verbose_name': 'Company Service',
                'verbose_name_plural': 'Company Services',
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
            },
        ),
    ]
