# Generated by Django 5.1.3 on 2024-11-10 07:05

import core.utils
import core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13')], max_length=2, verbose_name='Month')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Year')),
                ('balance_report_file', models.FileField(blank=True, null=True, upload_to=core.utils.GeneralUtils.rename_folder, validators=[core.validators.pdf_file_validator], verbose_name='Balance Report File')),
                ('profit_loss_file', models.FileField(blank=True, null=True, upload_to=core.utils.GeneralUtils.rename_folder, validators=[core.validators.pdf_file_validator], verbose_name='Profit Loss File')),
                ('sold_product_file', models.FileField(blank=True, null=True, upload_to=core.utils.GeneralUtils.rename_folder, validators=[core.validators.pdf_file_validator], verbose_name='Sold Product File')),
                ('account_turnover_file', models.FileField(blank=True, null=True, upload_to=core.utils.GeneralUtils.rename_folder, validators=[core.validators.pdf_file_validator], verbose_name='Account Turn Over File')),
                ('is_saved', models.BooleanField(default=True, verbose_name='Is Saved')),
                ('is_sent', models.BooleanField(default=True, verbose_name='Is Sent')),
            ],
            options={
                'verbose_name': 'Balance Report',
                'verbose_name_plural': 'Balance Reports',
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_active', models.BooleanField(default=False, verbose_name='Profile Active')),
                ('company_title', models.CharField(max_length=255, verbose_name='Company Title')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('social_code', models.CharField(max_length=10, unique=True, verbose_name='Social Code')),
                ('manager_name', models.CharField(max_length=255, verbose_name='Manager Full Name')),
                ('license', models.CharField(choices=[('n', 'Newbie'), ('i', 'Innovative'), ('l', 'Technological')], max_length=1, verbose_name='License Type')),
                ('insurance_list', models.PositiveSmallIntegerField(default=1, verbose_name='Insurance List')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profiles',
            },
        ),
        migrations.CreateModel(
            name='CompanyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activate')),
                ('purchased_date', models.DateField(auto_now_add=True, verbose_name='Purchased Date')),
            ],
            options={
                'verbose_name': 'Company Service',
                'verbose_name_plural': 'Company Services',
            },
        ),
        migrations.CreateModel(
            name='LifeCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital_providing', models.CharField(choices=[('operational', 'Operational'), ('finance', 'Finance'), ('invest', 'Invest')], default='operational', max_length=11, verbose_name='Capital Providing')),
            ],
            options={
                'verbose_name': 'Life Cycle',
                'verbose_name_plural': 'Life Cycles',
            },
        ),
        migrations.CreateModel(
            name='SpecialTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Special Tech',
                'verbose_name_plural': 'Special Techs',
            },
        ),
        migrations.CreateModel(
            name='TaxDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Year')),
                ('tax_file', models.FileField(blank=True, null=True, upload_to=core.utils.GeneralUtils.rename_folder, verbose_name='File')),
                ('is_saved', models.BooleanField(default=True, verbose_name='Is Saved')),
                ('is_sent', models.BooleanField(default=True, verbose_name='Is Sent')),
            ],
            options={
                'verbose_name': 'Tax Declaration',
                'verbose_name_plural': 'Tax Declarations',
            },
        ),
        migrations.CreateModel(
            name='TechField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Tech Field',
                'verbose_name_plural': 'Tech Fields',
            },
        ),
    ]
