# Generated by Django 5.1.2 on 2024-10-21 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital_providing', models.CharField(choices=[('operational', 'Operational'), ('finance', 'Finance'), ('invest', 'Invest')], default='operational', max_length=11, verbose_name='Capital Providing')),
                ('other_capital_providing', models.CharField(blank=True, max_length=20, null=True, verbose_name='Capital Providing Other')),
            ],
            options={
                'verbose_name': 'Life Cycle',
                'verbose_name_plural': 'Life Cycles',
            },
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='capital_providing_method',
            field=models.ManyToManyField(related_name='company_profile', to='company.lifecycle', verbose_name='Life Cycles'),
        ),
    ]
