# Generated by Django 5.1.2 on 2024-10-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_lifecycle_companyprofile_capital_providing_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='special_filed',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Special Field'),
        ),
    ]
