# Generated by Django 5.1.2 on 2024-10-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_companyprofile_special_filed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='capital_providing_method',
            field=models.ManyToManyField(related_name='company_profile', to='company.lifecycle', verbose_name='Capital Providing Method'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='license',
            field=models.CharField(choices=[(1, 'Newbie'), (2, 'Innovative'), (3, 'Technological')], max_length=15, verbose_name='License Type'),
        ),
    ]
