# Generated by Django 5.1.2 on 2024-10-26 11:00

import core.utils
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_remove_balancereport_prift_loss_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancereport',
            name='balance_report_file',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.GeneralUtils.rename_folder, validators=[core.validators.pdf_file_validator], verbose_name='Balance Report File'),
        ),
        migrations.AlterField(
            model_name='balancereport',
            name='profit_loss_file',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.GeneralUtils.rename_folder, validators=[core.validators.pdf_file_validator], verbose_name='Profit Loss File'),
        ),
        migrations.AlterField(
            model_name='balancereport',
            name='sold_product_file',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.GeneralUtils.rename_folder, validators=[core.validators.pdf_file_validator], verbose_name='Sold Product File'),
        ),
        migrations.AlterField(
            model_name='taxdeclaration',
            name='tax_file',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.GeneralUtils.rename_folder, verbose_name='File'),
        ),
    ]
