# Generated by Django 5.1.2 on 2024-10-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_companyprofile_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='license',
            field=models.CharField(choices=[('n', 'Newbie'), ('i', 'Innovative'), ('l', 'Technological')], max_length=1, verbose_name='License Type'),
        ),
    ]
