# Generated by Django 5.1.2 on 2024-10-21 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_companyprofile_license'),
        ('core', '0004_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service', verbose_name='Service'),
        ),
    ]
