# Generated by Django 5.1.2 on 2024-10-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_companyservice_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifecycle',
            name='other_capital_providing',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='profile_active',
            field=models.BooleanField(default=False, verbose_name='Profile Active'),
        ),
    ]
