# Generated by Django 5.1.2 on 2024-10-21 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_remove_lifecycle_other_capital_providing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Special Tech',
                'verbose_name_plural': 'Special Techs',
            },
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='special_filed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.specialtech', verbose_name='Special Field'),
        ),
    ]
