# Generated by Django 5.1.9 on 2025-05-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0011_alter_lifecycleplace_property"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lifecycleplace",
            name="property",
        ),
        migrations.AddField(
            model_name="lifecycleplace",
            name="property",
            field=models.ManyToManyField(
                related_name="life_cycle",
                to="company.lifecyclefeature",
                verbose_name="ویژگی",
            ),
        ),
    ]
