# Generated by Django 5.1.2 on 2024-10-21 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_techfield_remove_companyprofile_work_place_and_more'),
        ('core', '0004_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='address',
            field=models.CharField(default=1, max_length=255, verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.city', verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.province', verbose_name='Province'),
            preserve_default=False,
        ),
    ]
