# Generated by Django 5.1.2 on 2024-10-21 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_companyprofile_address_companyprofile_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='special_filed',
            new_name='special_field',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='organization',
        ),
    ]
