# Generated by Django 5.1.2 on 2024-10-22 07:53

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_rename_special_filed_companyprofile_special_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('file', models.FileField(blank=True, null=True, upload_to=core.utils.GeneralUtils.rename_folder, verbose_name='File')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='company.companyprofile', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Tax Declaration',
                'verbose_name_plural': 'Tax Declarations',
            },
        ),
    ]
