# Generated by Django 5.1.2 on 2024-10-22 08:34

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_taxdeclaration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='special_field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.specialtech', verbose_name='Special Field'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='tech_field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.techfield', verbose_name='Technical Field'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taxdeclaration',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.GeneralUtils.rename_folder, verbose_name='File'),
        ),
    ]
