# Generated by Django 5.1.9 on 2025-05-14 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0015_lifecycletheoritical_delete_lifecycleplace"),
    ]

    operations = [
        migrations.CreateModel(
            name="LifeCycleFinancialResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("operational", "عملیاتی"),
                            ("finance", "تامین مالی"),
                            ("invest", "سرمایه گذاری"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "چرخه عمر تامین مالی",
                "verbose_name_plural": "چرخه عمر تامین مالی",
            },
        ),
        migrations.AlterModelOptions(
            name="lifecycletheoritical",
            options={
                "verbose_name": "چرخه عمر جایگاه نظری",
                "verbose_name_plural": "چرخه عمر جایگاه نظری",
            },
        ),
        migrations.CreateModel(
            name="LifeCycleQuantitative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.companyprofile",
                        verbose_name="شرکت",
                    ),
                ),
                (
                    "resource",
                    models.ManyToManyField(
                        related_name="life_cycle",
                        to="company.lifecyclefinancialresource",
                        verbose_name="منابع",
                    ),
                ),
            ],
            options={
                "verbose_name": "چرخه عمر جایگاه کمی",
                "verbose_name_plural": "چرخه عمر جایگاه کمی",
            },
        ),
    ]
