# Generated by Django 5.1.9 on 2025-05-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0016_lifecyclefinancialresource_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lifecyclefinancialresource",
            options={
                "verbose_name": "چرخه عمر منابع مالی",
                "verbose_name_plural": "چرخه عمر منابع مالی",
            },
        ),
        migrations.AlterField(
            model_name="lifecyclequantitative",
            name="resource",
            field=models.ManyToManyField(
                blank=True,
                related_name="life_cycle",
                to="company.lifecyclefinancialresource",
                verbose_name="منابع",
            ),
        ),
    ]
