# Generated by Django 5.1.2 on 2024-10-23 05:12

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_alter_companyprofile_special_field_and_more'),
        ('core', '0006_alter_city_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.province', verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='special_field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.specialtech', verbose_name='Special Field'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='tech_field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.techfield', verbose_name='Technical Field'),
        ),
        migrations.AlterField(
            model_name='taxdeclaration',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taxfiles', to='company.companyprofile', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='taxdeclaration',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.GeneralUtils.rename_folder, verbose_name='File'),
        ),
        migrations.CreateModel(
            name='BalanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('balance_report_file', models.FileField(blank=True, null=True, upload_to=core.utils.GeneralUtils.rename_folder, verbose_name='Balance Report File')),
                ('prift_loss_file', models.FileField(blank=True, null=True, upload_to=core.utils.GeneralUtils.rename_folder, verbose_name='Prift Loss File')),
                ('sold_product_file', models.FileField(blank=True, null=True, upload_to=core.utils.GeneralUtils.rename_folder, verbose_name='Sold Product File')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportfiles', to='company.companyprofile', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Balance Report',
                'verbose_name_plural': 'Balance ReportS',
            },
        ),
    ]
