# Generated by Django 5.1.9 on 2025-05-17 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0017_alter_lifecyclefinancialresource_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LifeCycleTheoritical",
            new_name="LifeCycleTheoretical",
        ),
    ]
