# Generated by Django 5.1.2 on 2024-10-23 11:42

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_alter_balancereport_balance_report_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balancereport',
            options={'verbose_name': 'Balance Report', 'verbose_name_plural': 'Balance Reports'},
        ),
        migrations.AlterField(
            model_name='balancereport',
            name='balance_report_file',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.GeneralUtils.rename_folder, verbose_name='Balance Report File'),
        ),
        migrations.AlterField(
            model_name='balancereport',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportfiles', to='company.companyprofile', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='balancereport',
            name='prift_loss_file',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.GeneralUtils.rename_folder, verbose_name='Prift Loss File'),
        ),
        migrations.AlterField(
            model_name='balancereport',
            name='sold_product_file',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.GeneralUtils.rename_folder, verbose_name='Sold Product File'),
        ),
        migrations.AlterField(
            model_name='taxdeclaration',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxfiles', to='company.companyprofile', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='taxdeclaration',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.GeneralUtils.rename_folder, verbose_name='File'),
        ),
        migrations.AlterUniqueTogether(
            name='balancereport',
            unique_together={('company', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='taxdeclaration',
            unique_together={('company', 'year')},
        ),
    ]
