# Generated by Django 5.1.2 on 2024-10-23 12:31

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_alter_balancereport_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxdeclaration',
            name='file',
        ),
        migrations.AddField(
            model_name='taxdeclaration',
            name='tax_file',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.GeneralUtils.rename_folder, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='balancereport',
            name='balance_report_file',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.GeneralUtils.rename_folder, verbose_name='Balance Report File'),
        ),
        migrations.AlterField(
            model_name='balancereport',
            name='prift_loss_file',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.GeneralUtils.rename_folder, verbose_name='Prift Loss File'),
        ),
        migrations.AlterField(
            model_name='balancereport',
            name='sold_product_file',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.GeneralUtils.rename_folder, verbose_name='Sold Product File'),
        ),
    ]
