# Generated by Django 5.1.10 on 2025-08-20 16:28

import apps.management.models
import constants.validators.validators
import django.db.models.deletion
import django_lifecycle.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationChartBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field", models.CharField(max_length=150, verbose_name="زمینه")),
                (
                    "position_excel",
                    models.FileField(
                        max_length=150,
                        upload_to=apps.management.models.get_chart_excel_file_upload_path,
                        validators=[
                            constants.validators.validators.Validator.excel_file_validator
                        ],
                        verbose_name="فایل اکسل موقعیت",
                    ),
                ),
            ],
            options={
                "verbose_name": "فایل\u200c خام نمودار سازمانی",
                "verbose_name_plural": "فایل\u200cهای خام نمودار سازمانی",
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="HumanResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "excel_file",
                    models.FileField(
                        upload_to=apps.management.models.get_hr_file_upload_path,
                        validators=[
                            constants.validators.validators.Validator.excel_file_validator
                        ],
                        verbose_name="فایل اکسل",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="تأیید شده"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hrfiles",
                        to="company.companyprofile",
                        verbose_name="شرکت",
                    ),
                ),
            ],
            options={
                "verbose_name": "منابع انسانی شرکت\u200cها",
                "verbose_name_plural": "منابع انسانی شرکت\u200cها",
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PersonelInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="نام کامل")),
                (
                    "position",
                    models.CharField(max_length=150, verbose_name="موقعیت شغلی"),
                ),
                ("obligations", models.TextField(verbose_name="وظایف")),
                (
                    "is_exist",
                    models.BooleanField(default=False, verbose_name="موجود است"),
                ),
                (
                    "cooperates_with",
                    models.ManyToManyField(
                        blank=True,
                        to="management.personelinformation",
                        verbose_name="همکاری با (پرسنل)",
                    ),
                ),
                (
                    "human_resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personelinformation",
                        to="management.humanresource",
                        verbose_name="منابع انسانی",
                    ),
                ),
                (
                    "reports_to",
                    models.ManyToManyField(
                        blank=True,
                        to="management.personelinformation",
                        verbose_name="گزارش به (پرسنل)",
                    ),
                ),
            ],
            options={
                "verbose_name": "اطلاعات پرسنل",
                "verbose_name_plural": "اطلاعات پرسنل",
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.PositiveIntegerField(unique=True, verbose_name="کد موقعیت"),
                ),
                (
                    "position",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="موقعیت"
                    ),
                ),
            ],
            options={
                "verbose_name": "موقعیت شغلی",
                "verbose_name_plural": "موقعیت\u200cهای شغلی",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("code", "position"), name="unique_position_code"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="humanresource",
            constraint=models.UniqueConstraint(
                fields=("company",), name="unique_company_hr"
            ),
        ),
    ]
