# Generated by Django 5.1.10 on 2025-08-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personelinformation",
            name="reports_to",
            field=models.ManyToManyField(
                blank=True,
                related_name="subordinates",
                to="management.personelinformation",
                verbose_name="گزارش به (پرسنل)",
            ),
        ),
    ]
