# Generated by Django 5.1.9 on 2025-05-11 08:21

import apps.core.validators
import django.db.models.deletion
import apps.management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0005_alter_companyprofile_office_phone_number"),
        ("management", "0006_alter_swotoption_options_remove_swotmatrix_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="humanresource",
            options={
                "verbose_name": "منابع انسانی",
                "verbose_name_plural": "منابع انسانی",
            },
        ),
        migrations.AlterModelOptions(
            name="organizationchartbase",
            options={
                "verbose_name": "نمودار سازمانی",
                "verbose_name_plural": "نمودارهای سازمانی",
            },
        ),
        migrations.AlterModelOptions(
            name="personelinformation",
            options={
                "verbose_name": "اطلاعات پرسنل",
                "verbose_name_plural": "اطلاعات پرسنل",
            },
        ),
        migrations.AlterModelOptions(
            name="swotmatrix",
            options={
                "verbose_name": "ماتریس SWOT",
                "verbose_name_plural": "ماتریس\u200cهای SWOT",
            },
        ),
        migrations.AlterModelOptions(
            name="swotoption",
            options={
                "verbose_name": "گزینه SWOT",
                "verbose_name_plural": "گزینه\u200cهای SWOT",
            },
        ),
        migrations.AlterModelOptions(
            name="swotquestion",
            options={"verbose_name": "سوال SWOT", "verbose_name_plural": "سوالات SWOT"},
        ),
        migrations.AlterField(
            model_name="humanresource",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hrfiles",
                to="company.companyprofile",
                verbose_name="شرکت",
            ),
        ),
        migrations.AlterField(
            model_name="humanresource",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="humanresource",
            name="excel_file",
            field=models.FileField(
                upload_to=apps.management.models.get_hr_file_upload_path,
                validators=[apps.core.validators.Validator.excel_file_validator],
                verbose_name="فایل اکسل",
            ),
        ),
        migrations.AlterField(
            model_name="humanresource",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="تأیید شده"),
        ),
        migrations.AlterField(
            model_name="humanresource",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
        ),
        migrations.AlterField(
            model_name="organizationchartbase",
            name="field",
            field=models.CharField(max_length=150, verbose_name="زمینه"),
        ),
        migrations.AlterField(
            model_name="organizationchartbase",
            name="position_excel",
            field=models.FileField(
                max_length=150,
                upload_to=apps.management.models.get_chart_excel_file_upload_path,
                validators=[apps.core.validators.Validator.excel_file_validator],
                verbose_name="فایل اکسل موقعیت",
            ),
        ),
        migrations.AlterField(
            model_name="personelinformation",
            name="cooperates_with",
            field=models.ManyToManyField(
                blank=True,
                to="management.personelinformation",
                verbose_name="همکاری با (پرسنل)",
            ),
        ),
        migrations.AlterField(
            model_name="personelinformation",
            name="human_resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personelinformation",
                to="management.humanresource",
                verbose_name="منابع انسانی",
            ),
        ),
        migrations.AlterField(
            model_name="personelinformation",
            name="is_exist",
            field=models.BooleanField(default=False, verbose_name="موجود است"),
        ),
        migrations.AlterField(
            model_name="personelinformation",
            name="name",
            field=models.CharField(max_length=250, verbose_name="نام کامل"),
        ),
        migrations.AlterField(
            model_name="personelinformation",
            name="obligations",
            field=models.TextField(verbose_name="وظایف"),
        ),
        migrations.AlterField(
            model_name="personelinformation",
            name="position",
            field=models.CharField(max_length=150, verbose_name="موقعیت شغلی"),
        ),
        migrations.AlterField(
            model_name="personelinformation",
            name="reports_to",
            field=models.ManyToManyField(
                blank=True,
                to="management.personelinformation",
                verbose_name="گزارش به (پرسنل)",
            ),
        ),
        migrations.AlterField(
            model_name="swotmatrix",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="swot_matrices",
                to="company.companyprofile",
                verbose_name="شرکت",
            ),
        ),
        migrations.AlterField(
            model_name="swotmatrix",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="swotmatrix",
            name="options",
            field=models.ManyToManyField(
                related_name="swot_matrices",
                to="management.swotoption",
                verbose_name="گزینه\u200cهای SWOT",
            ),
        ),
        migrations.AlterField(
            model_name="swotmatrix",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
        ),
        migrations.AlterField(
            model_name="swotoption",
            name="answer",
            field=models.TextField(blank=True, null=True, verbose_name="پاسخ"),
        ),
        migrations.AlterField(
            model_name="swotoption",
            name="category",
            field=models.CharField(
                choices=[
                    ("Strength", "نقطه قوت"),
                    ("Weakness", "نقطه ضعف"),
                    ("Opportunity", "فرصت"),
                    ("Threat", "تهدید"),
                ],
                max_length=20,
                verbose_name="دسته\u200cبندی",
            ),
        ),
        migrations.AlterField(
            model_name="swotoption",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="company.companyprofile",
                verbose_name="شرکت",
            ),
        ),
        migrations.AlterField(
            model_name="swotoption",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="swotoption",
            name="external_factor",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Political", "سیاسی (مانند مقررات، سیاست\u200cهای دولتی)"),
                    ("Economic", "اقتصادی (مانند روندهای بازار، تورم)"),
                    ("Social", "اجتماعی (مانند تغییرات فرهنگی، جمعیت\u200cشناسی)"),
                    ("Technological", "فناوری (مانند نوآوری، اتوماسیون)"),
                    ("Environmental", "محیطی (مانند پایداری، تغییرات آب و هوایی)"),
                    ("Legal", "قانونی (مانند انطباق، قوانین)"),
                    ("None", "هیچ\u200cکدام"),
                ],
                max_length=50,
                verbose_name="عامل خارجی",
            ),
        ),
        migrations.AlterField(
            model_name="swotoption",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="management.swotquestion",
                verbose_name="سوال",
            ),
        ),
        migrations.AlterField(
            model_name="swotoption",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
        ),
        migrations.AlterField(
            model_name="swotquestion",
            name="category",
            field=models.CharField(
                choices=[
                    ("Strength", "نقطه قوت"),
                    ("Weakness", "نقطه ضعف"),
                    ("Opportunity", "فرصت"),
                    ("Threat", "تهدید"),
                ],
                max_length=50,
                verbose_name="دسته\u200cبندی",
            ),
        ),
        migrations.AlterField(
            model_name="swotquestion",
            name="text",
            field=models.TextField(unique=True, verbose_name="سوال"),
        ),
    ]
