# Generated by Django 5.1.9 on 2025-05-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0009_swotmatrix_is_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="swotanalysis",
            name="wt",
            field=models.TextField(verbose_name="تحلیل نقاط ضعف و تهدیدات"),
        ),
    ]
