# Generated by Django 5.1.9 on 2025-05-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0010_alter_swotanalysis_wt"),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.PositiveIntegerField(unique=True, verbose_name="کد موقعیت"),
                ),
                (
                    "position",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="موقعیت"
                    ),
                ),
            ],
            options={
                "verbose_name": "موقعیت شغلی",
                "verbose_name_plural": "موقعیت\u200cهای شغلی",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("code", "position"), name="unique_position_code"
                    )
                ],
            },
        ),
    ]
