# Generated by Django 5.1.10 on 2025-08-20 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                ("text", models.CharField(max_length=255, verbose_name="سوال")),
            ],
            options={
                "verbose_name": "سوال",
                "verbose_name_plural": "سوالات",
            },
        ),
        migrations.CreateModel(
            name="Questionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="عنوان")),
            ],
            options={
                "verbose_name": "پرسشنامه",
                "verbose_name_plural": "پرسشنامه\u200cها",
            },
        ),
        migrations.CreateModel(
            name="CompanyQuestionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Submitted At"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.companyprofile",
                        verbose_name="Company",
                    ),
                ),
                (
                    "questionnaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questionnaire.questionnaire",
                        verbose_name="Questionnaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Questionnaire",
                "verbose_name_plural": "Company Questionnaires",
            },
        ),
        migrations.CreateModel(
            name="QuestionChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.CharField(max_length=128, verbose_name="پاسخ")),
                ("points", models.IntegerField(verbose_name="امتیاز")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="questionnaire.question",
                        verbose_name="سوال",
                    ),
                ),
            ],
            options={
                "verbose_name": "گزینه\u200c سوال",
                "verbose_name_plural": "گزینه\u200cهای سوالات",
            },
        ),
        migrations.CreateModel(
            name="QuestionnaireQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="عدد ترتیب"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questionnaire.question",
                        verbose_name="سوال",
                    ),
                ),
                (
                    "questionnaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questionnaire.questionnaire",
                        verbose_name="پرسشنامه",
                    ),
                ),
            ],
            options={
                "verbose_name": "سوال پرسشنامه",
                "verbose_name_plural": "سوالات پرسشنامه\u200cها",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="questions",
            field=models.ManyToManyField(
                through="questionnaire.QuestionnaireQuestion",
                to="questionnaire.question",
                verbose_name="سوالات",
            ),
        ),
        migrations.CreateModel(
            name="CompanyAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answered_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Answered At"),
                ),
                (
                    "company_questionnaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="questionnaire.companyquestionnaire",
                        verbose_name="Company Questionnaire",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questionnaire.question",
                        verbose_name="Question",
                    ),
                ),
                (
                    "selected_choice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="questionnaire.questionchoice",
                        verbose_name="Selected Choice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Answer",
                "verbose_name_plural": "Company Answers",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company_questionnaire", "question"),
                        name="unique_company_answer_for_question",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="QuestionMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="Title")),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Weight"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="questionnaire.question",
                        verbose_name="سوال",
                    ),
                ),
            ],
            options={
                "verbose_name": "شاخص سوال",
                "verbose_name_plural": "شاخص\u200cهای سوالات",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("question", "title"), name="unique_question_metric"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="questionnairequestion",
            constraint=models.UniqueConstraint(
                fields=("questionnaire", "question"),
                name="unique_questionnaire_question",
            ),
        ),
    ]
