# Generated by Django 5.1.10 on 2025-08-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyquestionnaire",
            name="submitted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Submitted At"
            ),
        ),
    ]
