# Generated by Django 5.1.10 on 2025-08-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0002_alter_companyquestionnaire_submitted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnaire",
            name="counter",
            field=models.IntegerField(default=0),
        ),
    ]
