# Generated by Django 5.1.10 on 2025-08-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0003_questionnaire_counter"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyquestionnaire",
            name="question_counter",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="counter",
            field=models.IntegerField(default=0, verbose_name="Number of Questions"),
        ),
    ]
