# Generated by Django 5.1.10 on 2025-09-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0004_companyquestionnaire_question_counter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyquestionnaire",
            name="question_counter",
            field=models.IntegerField(default=0),
        ),
    ]
