# Generated by Django 5.1.10 on 2025-09-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0005_alter_companyquestionnaire_question_counter"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnaire",
            name="slug",
            field=models.CharField(
                default="",
                max_length=20,
                unique=True,
                verbose_name=" اسلاگ - شناسه یکتا",
            ),
        ),
    ]
