# Generated by Django 5.1.10 on 2025-09-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0006_questionnaire_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questionnaire",
            name="slug",
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="id",
            field=models.CharField(
                default="",
                max_length=20,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name=" آیدی - شناسه یکتا",
            ),
        ),
    ]
