# Generated by Django 5.1.10 on 2025-09-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0007_remove_questionnaire_slug_alter_questionnaire_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionnaire",
            name="id",
            field=models.CharField(
                max_length=20,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name=" آیدی - شناسه یکتا",
            ),
        ),
    ]
