# Generated by Django 5.1.10 on 2025-09-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0008_alter_questionnaire_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionmetric",
            name="weight",
            field=models.DecimalField(
                decimal_places=4, max_digits=4, verbose_name="Weight"
            ),
        ),
    ]
