# Generated by Django 5.1.10 on 2025-08-20 23:29

import apps.swot.models
import django.db.models.deletion
import django_lifecycle.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SWOTQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(unique=True, verbose_name="Text")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Strength", "Strength"),
                            ("Weakness", "Weakness"),
                            ("Opportunity", "Opportunity"),
                            ("Threat", "Threat"),
                        ],
                        max_length=50,
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "SWOT Question",
                "verbose_name_plural": "SWOT Questions",
            },
        ),
        migrations.CreateModel(
            name="SWOTMatrix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "matrix_type",
                    models.CharField(
                        choices=[
                            ("q", "Questionnaire"),
                            ("i", "Inferential"),
                            ("e", "Elective"),
                        ],
                        max_length=15,
                        verbose_name="Type",
                    ),
                ),
                (
                    "opportunity",
                    apps.swot.models.SWOTJSONField(verbose_name="Opportunity"),
                ),
                ("threat", apps.swot.models.SWOTJSONField(verbose_name="Threat")),
                ("weakness", apps.swot.models.SWOTJSONField(verbose_name="Weakness")),
                ("strength", apps.swot.models.SWOTJSONField(verbose_name="Strength")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swot",
                        to="company.companyprofile",
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "SWOT Matrix",
                "verbose_name_plural": "SWOT Matrices",
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="SWOTAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                ("so", models.TextField(verbose_name="SO Analysis")),
                ("st", models.TextField(verbose_name="ST Analysis")),
                ("wo", models.TextField(verbose_name="WO Analysis")),
                ("wt", models.TextField(verbose_name="WT Analysis")),
                (
                    "matrix",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="swot.swotmatrix",
                        verbose_name="Matrix",
                    ),
                ),
            ],
            options={
                "verbose_name": "SWOT Analysis",
                "verbose_name_plural": "SWOT Analysis",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SWOTOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option", models.CharField(max_length=50, verbose_name="Option")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Strength", "Strength"),
                            ("Weakness", "Weakness"),
                            ("Opportunity", "Opportunity"),
                            ("Threat", "Threat"),
                        ],
                        max_length=50,
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "SWOT Option",
                "verbose_name_plural": "SWOT Options",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("option", "category"), name="unique_swot_option"
                    )
                ],
            },
        ),
    ]
