# Generated by Django 5.1.10 on 2025-08-20 16:28

import apps.salesdata.services.salesdata_service
import constants.validators.validators
import django.core.validators
import django.db.models.deletion
import django_lifecycle.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerSaleData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, verbose_name="Name(Person/Company)"
                    ),
                ),
                (
                    "sale_area",
                    models.CharField(
                        choices=[("d", "Domestic"), ("f", "Foreign")],
                        max_length=1,
                        verbose_name="Sale Area",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("so", "Social"),
                            ("on", "Online"),
                            ("se", "Seo"),
                            ("em", "Email"),
                            ("ph", "Phone"),
                            ("ex", "Exhibition"),
                            ("pe", "People"),
                            ("ot", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("city", models.CharField(max_length=20, verbose_name="City")),
                (
                    "first_purchase_date",
                    models.DateField(verbose_name="First Purchase Date"),
                ),
                (
                    "last_purchase_date",
                    models.DateField(verbose_name="Last Purchase Date"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_data",
                        to="company.companyprofile",
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Sale Data",
                "verbose_name_plural": "Customers Sale Data",
            },
        ),
        migrations.CreateModel(
            name="CustomerSaleFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.salesdata.services.salesdata_service.SaleDataService.set_customer_data_file_upload_path,
                        validators=[
                            constants.validators.validators.Validator.excel_file_validator
                        ],
                        verbose_name="File",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_data_files",
                        to="company.companyprofile",
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Sale File",
                "verbose_name_plural": "Customer Sale Files",
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="DomesticSaleData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "factor_number",
                    models.PositiveSmallIntegerField(verbose_name="Factor Number"),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=255, verbose_name="Customer Name"),
                ),
                (
                    "product_code",
                    models.PositiveSmallIntegerField(verbose_name="Product Code"),
                ),
                (
                    "product_name",
                    models.CharField(max_length=50, verbose_name="Product Name"),
                ),
                (
                    "sold_amount",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="No Value less than 0 are allowed"
                            )
                        ],
                        verbose_name="Sold Amount",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Unit Price"
                    ),
                ),
                (
                    "discount_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Discount Price"
                    ),
                ),
                (
                    "sale_method",
                    models.CharField(
                        choices=[("online", "Online"), ("offline", "Offline")],
                        default="online",
                        max_length=7,
                        verbose_name="Sale Method",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("cash", "Cash"), ("installment", "Installment")],
                        default="cash",
                        max_length=11,
                        verbose_name="Payment Method",
                    ),
                ),
                ("sold_at", models.DateField(verbose_name="Sold At")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domestic_sales",
                        to="company.companyprofile",
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Domestic Sale",
                "verbose_name_plural": "Domestic Sales",
            },
        ),
        migrations.CreateModel(
            name="DomesticSaleFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.salesdata.services.salesdata_service.SaleDataService.set_domestic_data_file_upload_path,
                        validators=[
                            constants.validators.validators.Validator.excel_file_validator
                        ],
                        verbose_name="File",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domestic_sale_files",
                        to="company.companyprofile",
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Domestic Sale File",
                "verbose_name_plural": "Domestic Sale Files",
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ProductData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, verbose_name="Product/Service Code"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("me", "Metre"),
                            ("sm", "Square Metre"),
                            ("g", "Gram"),
                            ("kg", "Kilo Gram"),
                            ("t", "Ton"),
                            ("n", "Number"),
                            ("cc", "CC"),
                            ("l", "Litre"),
                            ("h", "Hour"),
                            ("mi", "Minute"),
                            ("o", "Other"),
                        ],
                        max_length=50,
                        verbose_name="Unit",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="company.companyprofile",
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product/Service Data",
                "verbose_name_plural": "Products/Services Data",
            },
        ),
        migrations.CreateModel(
            name="ForeignSaleData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=255, verbose_name="Customer Name"),
                ),
                (
                    "sold_amount",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="No Value less than 0 are allowed"
                            )
                        ],
                        verbose_name="Sold Amount",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Unit Price"
                    ),
                ),
                ("contract_date", models.DateField(verbose_name="Contract Date")),
                ("delivery_date", models.DateField(verbose_name="Delivery Date")),
                (
                    "target_country",
                    models.CharField(max_length=50, verbose_name="Target Country"),
                ),
                ("area", models.CharField(max_length=50, verbose_name="Area")),
                (
                    "customer_approval",
                    models.BooleanField(default=True, verbose_name="Customer Approval"),
                ),
                (
                    "sale_method",
                    models.CharField(
                        choices=[("online", "Online"), ("exhibition", "Exhibition")],
                        default="online",
                        max_length=10,
                        verbose_name="Sale Method",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("ap", "Advance Payment"),
                            ("oa", "Open Account"),
                            ("re", "Receivable"),
                            ("do", "Document"),
                        ],
                        default="ap",
                        max_length=10,
                        verbose_name="Payment Status",
                    ),
                ),
                (
                    "transfer_condition",
                    models.CharField(
                        choices=[
                            ("land", "Land"),
                            ("rail", "Rail"),
                            ("sea", "Sea"),
                            ("air", "Air"),
                        ],
                        default="air",
                        max_length=10,
                        verbose_name="Transfer Condition",
                    ),
                ),
                (
                    "trading_currency",
                    models.CharField(max_length=10, verbose_name="Trading Currency"),
                ),
                (
                    "exchange_rate",
                    models.CharField(max_length=10, verbose_name="Exchange Rate"),
                ),
                (
                    "sale_amount",
                    models.CharField(max_length=10, verbose_name="Sale Amount"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="foreign_sales",
                        to="company.companyprofile",
                        verbose_name="Company",
                    ),
                ),
                (
                    "product_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="foreign_sale",
                        to="salesdata.productdata",
                        verbose_name="Product Code",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foreign Sale",
                "verbose_name_plural": "Foreign Sales",
            },
        ),
        migrations.CreateModel(
            name="ProductDataFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.salesdata.services.salesdata_service.SaleDataService.set_product_data_file_upload_path,
                        validators=[
                            constants.validators.validators.Validator.excel_file_validator
                        ],
                        verbose_name="File",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_data_files",
                        to="company.companyprofile",
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product/Service Data File",
                "verbose_name_plural": "Products/Services Data Files",
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ProductLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=120, verbose_name="Product"),
                ),
                (
                    "production_date",
                    models.DateField(
                        help_text="The date of production.",
                        verbose_name="Production Date",
                    ),
                ),
                (
                    "total_produced",
                    models.PositiveIntegerField(
                        help_text="Total number of units produced on this date.",
                        verbose_name="Total Production Count",
                    ),
                ),
                (
                    "total_returned",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of units returned from customers.",
                        verbose_name="Returned Products Count",
                    ),
                ),
                (
                    "total_rejected",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of units that failed quality control.",
                        verbose_name="Rejected Products Count",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Unit Price"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products_log",
                        to="company.companyprofile",
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Log",
                "verbose_name_plural": "Product Logs",
            },
        ),
        migrations.CreateModel(
            name="ProductLogFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.salesdata.services.salesdata_service.SaleDataService.set_product_logs_file_upload_path,
                        validators=[
                            constants.validators.validators.Validator.excel_file_validator
                        ],
                        verbose_name="File",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_log_files",
                        to="company.companyprofile",
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Log File",
                "verbose_name_plural": "Product Logs Files",
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
